### ISSUE TITLE
UPSERT Operations using Hive Connectors

### ISSUE THREAD

**Issue by sumeetgupta07** [delta-io/connectors#100]
Delta only supports read operations through Hive.
This issue is a functionality addition request to allow INSERT/UPDATE/DELETE operations through Hive

**Comment by zsxwing** [comment]
Thanks for opening the ticket. We will visit this when #85 is done.

**Comment by zsxwing** [comment]
cc @YannByron as you would like to build this. We can start from INSERT INTO support.

**Comment by vkorukanti** [comment]
This repo has been deprecated and the code is moved under `connectors` module in https://github.com/delta-io/delta repository. Please create the issue in repository https://github.com/delta-io/delta. See delta-io/connectors#556 for details.
