### ISSUE TITLE
PowerBI: Add support for TIMESTAMP AS OF 

### ISSUE THREAD

**Issue by gbrueckl** [delta-io/connectors#104]
Beside the already existing support for `VERSION AS OF`, it should also be possible to query a Delta lake table using `TIMESTAMP AS OF` in a similar way - e.g. as part of the optional second parameter

**Comment by dennyglee** [comment]
Great enhancement idea - let's do it! :)

**Comment by vkorukanti** [comment]
This repo has been deprecated and the code is moved under `connectors` module in https://github.com/delta-io/delta repository. Please create the issue in repository https://github.com/delta-io/delta. See delta-io/connectors#556 for details.
