### ISSUE TITLE
Delta Source for Apache Flink

### ISSUE THREAD

**Issue by dennyglee** [delta-io/connectors#110]
Build a Flink/Delta source (i.e., Flink reads from Delta Lake) potentially leveraging the [Delta Standalone Reader](https://github.com/delta-io/connectors#delta-standalone-reader).  Expansion of issue #74 .

## PR Plan:
- PR 5 - Option support in Bounded Mode - **DONE**
- PR 6 - Continuous mode without monitoring for changes - **DONE**
- PR 6.1 - Package Refactoring - **DONE**
- PR 7 - Monitoring for changes in Continuous mode - **DONE**
- PR 7.1 - More tests for PR 7 including IT case tests for Continuous mode. - **DONE**
- PR 9 - Builder - **DONE**
- PR 10 - Builder refactoring to extract Schema from Delta Log. - **DONE**
- PR 10.1 - Tests for SourceUtils::buildSourceSchema, DeltaSourceBuilderBase::getSourceSchema and SnapshotSupplier implementations. - **DONE**
- PR 11 - Partition Support using Delta log to identify partition columns. - **DONE**
- PR 12 - Get BATCH_SIZE for Format builder from Source options - this value is currently hardcoded. Add validation for option names and values including using not applicable options for given mode via generic option method. - **DONE**
- **PR 12.1 More tests To option type conversion + handling option(...) validation errors.** - **DONE**
- PR 13 - Use new DeltaLog API `getVersionAtOrAfterTimestamp` for continuous `getChanges` call when using `starting timestamp`. This uses the "streaming" semantics of timestamp -> version conversion. - **DONE**
- @scottsand-db -> review Java docs.
- PR 14 - Additional IT tests including all options and end to end tests using Source and Sink. - **DONE**
- After PR 14 run Sample job using Delta Sink/Source on a  real cluster. - **DONE**
- PR 15 - simple test case for remote file table path, similar to #340 and #341 - **DONE**
- PR 16 - update README - **DONE**
- PR 17 - update examples - **DONE**
- <s>PR 18 - add "columnNames" key support to `.option(....)`</s>
- PR 19 - Flink Sink integration test that creates a Delta Log checkpoint and asserts its correctness - **DONE**
- PR 20 - update javadocs - ** DONE**

-- All functionalities are in place up to this point. The following PRs are extra tests, eventual bug fixes and code/javadoc adjustments. --

**P1 Functionalities** 
- Aggregate and report as one all option validation errors from Source Builder. 
- continuous from version 0, handling Metadata & Protocol actions.
- source metrics. also update readme.

~~PR 11 - Annotate with @deprecated  Sink's builder methods that names starts from "with". Add new ones without "with" prefix and overload partitions with List argument for Sink.~~

## TODOs
- Use index for keeping track of already processed paths in SnapshotProcessor - needs new Delta API.
- Re-visit Delta Standalone APIs for when the source see's metadata/protocol actions. Update ActionProcessor class to handle MetaData and Protocol Actions

**Comment by kristoffSC** [comment]
Regarding point:  "After PR 14 run Sample job using Delta Sink/Source on a real cluster."

Basic manual tests were executed on Flink cluster running on a local docker setup.
Task Manager and Job Manager nodes were using shared docker volue to read from and write to Delta tables.

Performed tests:
- Bounded mode: Delta Table -> Flink Source -> Flink Sink
Source parallelism level = 3
Sink parallelism level = 3
![DeltaEndToEnd](https://user-images.githubusercontent.com/7932805/174852340-8e66bac9-2329-42e3-ab53-cb5af0214190.PNG)

Source and Sink parallelism level = 3
![DeltaEndToEnd2](https://user-images.githubusercontent.com/7932805/174852402-66298629-f2fe-4a02-a42c-c3d5855d6edc.PNG)


- Continuous mode
Test setup:
One job running two pipelines.
First pipeline contains a custom source generating continuous stream of events and Flink Delta Sink, that writes data into Delta table.

Second pipeline contains Delta Source setup to work in continuous mode and to read Delta table created by the first pipeline. Source is followed by another Delta Sink.
![StreamingEndToEnd](https://user-images.githubusercontent.com/7932805/174853165-640356aa-99d0-407f-97b2-8b978086a744.PNG)

**Comment by scottsand-db** [comment]
Latest javadocs as of commit eaab5866bb7d2c9240fb97c09fc48925a25510da
[0.5.0-SNAPSHOT.zip](https://github.com/delta-io/connectors/files/9094464/0.5.0-SNAPSHOT.zip)

**Comment by tdas** [comment]
this has been released in Delta connectors 0.5.0
