### ISSUE TITLE
Delta Spout for Apache Heron

### ISSUE THREAD

**Issue by nicknezis** [delta-io/connectors#121]
Build a Heron/Delta source (i.e., Heron reads from Delta Lake) potentially leveraging the Delta Standalone Reader. Expansion of issue #74 which was created for Flink. If created properly, this could also benefit Apache Storm.

**Comment by dennyglee** [comment]
Thanks @nicknezis  - could you add a comment to the [Delta OSS Roadmap 2021 H2](http://github.com/delta-io/delta/issues/748) to garner community interest?  Thanks!
