### ISSUE TITLE
Delta Sink for Apache Heron

### ISSUE THREAD

**Issue by nicknezis** [delta-io/connectors#122]
Build a Heron/Delta sink (i.e., Heron bolt writes to Delta Lake) potentially leveraging the Delta Standalone Writer per #85. This issue expands on #74 (which was made for Flink).

**Comment by vkorukanti** [comment]
This repo has been deprecated and the code is moved under `connectors` module in https://github.com/delta-io/delta repository. Please create the issue in repository https://github.com/delta-io/delta. See delta-io/connectors#556 for details.
