### ISSUE TITLE
Support to define partition columns to create external table

### ISSUE THREAD

**Issue by YannByron** [delta-io/connectors#128]
For now, for a partitioned delta table, we can use sql as followed to create external table.

`CREATE EXTERNAL TABLE  tableName (col1 string, pt string)
ROW FORMAT SERDE  'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe'
STORED BY 'io.delta.hive.DeltaStorageHandler
LOCATION  '/path/to/delta/table'`

But, I wish to use sql as followed to do this, obviously define the partition columns. I think this way will be more suitable to hive-style ：

`CREATE EXTERNAL TABLE  tableName (col1 string) partitioned by (pt string)
ROW FORMAT SERDE  'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe'
STORED BY 'io.delta.hive.DeltaStorageHandler
LOCATION  '/path/to/delta/table'`

In the current delta-connectors implementation, the exception will be raised:
`Found partition columns (pt)  in table db.tableName. The partition columns in a Delta table will be read from its own metadata and should not be set manually`

If okey, I wanna work for this. Plz think about it, and i wait for your reply.

@zhu @scottsand-db

**Comment by zsxwing** [comment]
Closing this as per the discussion in #132.
