### ISSUE TITLE
[Question] Can Delta Standalone Reader read specific partition instead of all partition?

### ISSUE THREAD

**Issue by axiangcoding** [delta-io/connectors#135]
I only need to calculate the amount of data in specific partition in a spring application. I don’t need to read all the data. Is the function to read a specific partition currently available? 
I see that there is no description in the document

**Comment by axiangcoding** [comment]
This question is very similar to [https://groups.google.com/g/delta-users/c/qMYF7_5xghk/m/42sZKwCKAwAJ](https://groups.google.com/g/delta-users/c/qMYF7_5xghk/m/42sZKwCKAwAJ) , but it seems that there is no clear answer in the community?

**Comment by zsxwing** [comment]
Yep. This sounds useful. Feel free to open a PR 😄

**Comment by axiangcoding** [comment]
> Yep. This sounds useful. Feel free to open a PR 😄

Thanks, I have found a way, but I am new to scala, it will take some time

**Comment by noslowerdna** [comment]
I agree that it seems like a worthwhile enhancement - something along the lines of being able to supply a map of partition key-values should be relatively straightforward.

**Comment by wwang-talend** [comment]
similar to this pr provided? https://github.com/delta-io/connectors/pull/76/files

**Comment by noslowerdna** [comment]
@wwang-talend Yes I believe so. That PR is on the right track I think, I didn't know about it until you pointed it out. I added a couple comments to it. Would be nice to get it merged.

@zsxwing Yes it would be useful to have this feature.

**Comment by scottsand-db** [comment]
@axiangcoding with the release of [Delta Standalone 0.3.0](https://github.com/delta-io/connectors/releases/tag/v0.3.0
) we now support "Partition filtering for metadata reads".

Check out the [Java API docs](https://delta-io.github.io/connectors/latest/delta-standalone/api/java/index.html) for `Snapshot.scan(predicate)`.

**Comment by scottsand-db** [comment]
If that meets your requirement, please close this ticket.

**Comment by axiangcoding** [comment]
Good job! This should do what i need, thanks a lot
