### ISSUE TITLE
The Delta table schema is not the same as the Hive schema. 

### ISSUE THREAD

**Issue by zhangxinjian123** [delta-io/connectors#17]
Why is it inconsistent? I checked that the schema of delta table and hive table are correct and the quantity is the same	

at org.apache.hadoop.util.RunJar.main(RunJar.java:227)
Caused by: MetaException(message:The Delta table schema is not the same as the Hive schema. Please update your Hive
table's schema to match the Delta table schema.
Delta table schema: StructType(StructField(types,StringType,true), StructField(tableName,StringType,true), StructField(primaryKey,StringType,true), StructField(timesmap,StringType,true), StructField(id,StringType,true), StructField(task_id,StringType,true), StructField(order_id,StringType,true), StructField(task_name,StringType,true), StructField(display_name,StringType,true), StructField(task_state,StringType,true), StructField(create_time,StringType,true), StructField(update_time,StringType,true), StructField(end_time,StringType,true), StructField(parent_task_id,StringType,true), StructField(variable,StringType,true), StructField(trade_id,StringType,true), StructField(partition,StringType,true))
Hive schema: struct<types:string,tablename:string,primarykey:string,timesmap:string,id:string,task_id:string,order_id:string,task_name:string,display_name:string,task_state:string,create_time:string,update_time:string,end_time:string,parent_task_id:string,variable:string,trade_id:string,partition:string>)
	at org.apache.spark.sql.delta.DeltaHelper$.metaInconsistencyException(DeltaHelper.scala:252)
	at org.apache.spark.sql.delta.DeltaHelper$.checkTableSchema(DeltaHelper.scala:176)
	at io.delta.hive.DeltaStorageHandler.preCreateTable(DeltaStorageHandler.scala:195)

**Comment by zsxwing** [comment]
Thanks for reporting this. This is because Hive will convert all column names to lower case by default, but Delta preserves the case. I will make a change to make the schema comparison case insensitive.
