### ISSUE TITLE
Hive: Add `AS OF` syntax support

### ISSUE THREAD

**Issue by spmp** [delta-io/connectors#202]
It would be _very_ helpful for the Hive connector to support the `AS OF` syntax - for example `TIMESTAMP AS OF` and `VERSION AS OF`.
 The Spark SQL interface is going through a PR now 8) (https://github.com/apache/spark/pull/34497)

Currently I have Spark batch processes to create end of day views, this would enable Hive users to do this directly.

**Comment by zsxwing** [comment]
@spmp thanks for raising this. We would need to push the syntax to Hive so that the connector can use it, similar to the Spark PR. Could you raise a requirement in https://issues.apache.org/jira/browse/HIVE and see what the hive community replies?

**Comment by huaxingao** [comment]
FYI: https://issues.apache.org/jira/browse/HIVE-25344

**Comment by zsxwing** [comment]
@huaxingao Thanks for the information. Will try it when Hive 4.0.0 is out.

**Comment by spmp** [comment]
@zsxwing, as Hive 4.1 is now out, what can we do to get this feature implemented. I am happy to try my possibly useless hand at it 8) This is a killer feature for me 🤗 Happy to do real world testing on scared SAS users 8)

**Comment by zsxwing** [comment]
@spmp I haven't looked at what is done by https://issues.apache.org/jira/browse/HIVE-25344. I'd suggest you to look at what interface added by Hive and see if Delta can plugin its code to this interface.

**Comment by vkorukanti** [comment]
This repo has been deprecated and the code is moved under `connectors` module in https://github.com/delta-io/delta repository. Please create the issue in repository https://github.com/delta-io/delta. See delta-io/connectors#556 for details.
