### ISSUE TITLE
OptimisticTransactionImpl.commit should turn absolute paths to relative paths if possible

### ISSUE THREAD

**Issue by zsxwing** [delta-io/connectors#228]
When users call `OptimisticTransactionImpl.commit`, they may use absolution paths in `AddFile/RemoveFile`. It would be great to change absolute paths to relative paths if these paths are under the table path.

**Comment by allisonport-db** [comment]
Probably just https://docs.oracle.com/javase/7/docs/api/java/net/URI.html#relativize(java.net.URI). If not a prefix it'll return the original path. I can add this later?

**Comment by scottsand-db** [comment]
@allisonport-db do you have bandwidth to take this on?
