### ISSUE TITLE
OptimisticTransactionImpl: add extra warning when incorrectly updating the table Protocol

### ISSUE THREAD

**Issue by scottsand-db** [delta-io/connectors#229]
Currently, since DSW 0.3.0 only supports a single protocol version (1, 2), when users try to [change the protocol using metadata.configuration in OptimisticTransaction](https://github.com/delta-io/connectors/blob/master/standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala#L181), we ignore those changes.

In addition to ignoring those changes, we should log a warning, too.

**Comment by zsxwing** [comment]
Shouldn't io.delta.standalone.internal.actions.Protocol#checkMetadataProtocolProperties fail if we see these properties? Do I miss anything?

**Comment by scottsand-db** [comment]
@zsxwing that's right, we will fail if we see that. What this issue is suggesting is that before that stage, when we first see that `metadata.configuration` contains protocol specs, and when we remove those protocol specs (so that we do not later fail), we should also log an exception.

Else the user has just run an operation in which they tried to update the protocol version of the table, and there is no visible feedback that that operation was not successful (whereas in reality, we just ignored their change).

**Comment by allisonport-db** [comment]
Why would we want a different behavior for metadata updated with `updateMetadata` vs `commit`? (failure vs ignore change & log warning)

 And along those lines can we consolidate:
```scala
private def prepareCommit(actions: Seq[Action]): Seq[Action] = {
    ...
    actions.foreach { case m: Metadata => 
        updateMetadata(m)
        verifySchemaCompatibility(snapshot.metadataScala.schema, m.schema, actions)
    }

    // If the metadata has changed, add that to the set of actions
    var finalActions = newMetadata.toSeq ++ actions
    ...
}
```
and 
```scala
override def updateMetadata(metadataJ: MetadataJ): Unit = {
    ...
    val noProtocolVersionConfig = latestMetadata.configuration.filter {
      case (Protocol.MIN_READER_VERSION_PROP, _) => false // log warning
      case (Protocol.MIN_WRITER_VERSION_PROP, _) => false // log warning
      case _ => true
    }
   ...
}
```

**Comment by scottsand-db** [comment]
I'm AFK right now (EST hours). We can discuss this tomorrow

**Comment by scottsand-db** [comment]
Good catch. We should have the same behaviour. Can you expand your solution a bit more? for example, right now if a Metadata is added to actions, we will fail on `assert(metadataChanges.length <= 1`, since the Metadata wasn't removed from actions.

Here's my idea:

Let's make some invariants:
- any Metadata action to be committed will go through `updateMetadata`, either directly or extracted from the actions passed to `commit`
- the actions passed to `prepareCommit` will never contain a metadata

```
override def commit[T <: ActionJ](
      actionsJ: java.lang.Iterable[T],
      op: Operation,
      engineInfo: String): CommitResult = {

    val metadataActions = actionsJ.asScala.collect { case m: MetadataJ => m }
    assert(
      metadataActions.size <= 1 && (metadataActions.isEmpty || newMetadata.isEmpty),
      "Cannot change the metadata more than once in a transaction")
    metadataActions.headOption.foreach(updateMetadata)

    val actions = actionsJ.asScala
      .map(ConversionUtils.convertActionJ)
      .filter(!_.isInstanceOf[Metadata])
      .toSeq

...
// update scaladoc with our invariants
private def prepareCommit(actions: Seq[Action]): Seq[Action] = {
...
assert(metadataChanges.length <= 1, // ------ we could even delete this too
      "Cannot change the metadata more than once in a transaction.")

metadataChanges.foreach { m =>
      verifyNewMetadata(m) // ------ DELETE
      verifySchemaCompatibility(snapshot.metadataScala.schema, m.schema, actions)
    }
```

**Comment by zsxwing** [comment]
It looks like we can just disallow `metadata` to be passed into `commit`. This would be much easier to understand.

```
val noProtocolVersionConfig = latestMetadata.configuration.filter {
      case (Protocol.MIN_READER_VERSION_PROP, _) => false // log warning
      case (Protocol.MIN_WRITER_VERSION_PROP, _) => false // log warning
      case _ => true
    }
```
By the way, if `Protocol.MIN_READER_VERSION_PROP` and `Protocol.MIN_WRITER_VERSION_PROP` is not (1, 2), we should fail. These properties need to be respected.

**Comment by scottsand-db** [comment]
Just to be clear: << It looks like we can just disallow metadata to be passed into commit >> . So we will throw an error?

That sounds fine with me. And we update the javadoc + scaladocs to indicate this.

**Comment by zsxwing** [comment]
> So we will throw an error?

Yep. If the user complains, we can change to accept metadata in future. But cannot change from `no error` to `error`.

**Comment by allisonport-db** [comment]
This change would mean to create a new table you'd have to do
```scala
val log = DeltaLog.forTable(...)
val txn = log.startTransaction()
txn.updateMetadata(newMetadata)
txn.commit(Nil, ...)
```
This seems unintuitive to me (and would break basically all our test suites).

**Comment by scottsand-db** [comment]
Breaking test suites is fine I think. Having the best API is most important.

Is there some documentation we could add that would make it more intuitive?

**Comment by allisonport-db** [comment]
I just mean it as an example of why it's unintuitive.

What if you can update the metadata in `commit` or `updateMetadata`, and the only invariant to the user is still that they can only commit (through either method or both) one *unique* metadata instance.

To do this we just:
- Pass any metadata actions found in commit into prepareMetadata
- Add `newMetadataJ : Option[MetadataJ]` and only fail for more than one `Metadata`s in `updateMetadata` if a second *different* instance is provided (via any avenue)

Then our one source of truth is `updateMetadata`.

**Comment by zsxwing** [comment]
If there are a lot of tests to fix, we can just use @scottsand-db 's proposal:

> * any Metadata action to be committed will go through `updateMetadata`, either directly or extracted from the actions passed to `commit`
> * the actions passed to `prepareCommit` will never contain a metadata

I'm okay with that.
