### ISSUE TITLE
Flink SQL/TableAPI/Catalog Support

### ISSUE THREAD

**Issue by tdas** [delta-io/connectors#238]
This is a general issue to discuss requirements, goals, and the project plan of the work to be done to add SQL/TableAPI support to the flink-delta connector, as well as to implement a Delta catalog for flink.

Here's the public design doc for catalog support: https://docs.google.com/document/d/1L31_CDgVZjy5N4qe7VdDftKn0YAvwSg6Zh2PxQqpIuM/edit#

And here's a rough project plan we should follow
- [FlinkSQL_PR_1] Flink Delta Sink - Table API - MERGED
- [FlinkSQL_PR_2] Flink Delta Source- Table API - MERGED
- [FlinkSQL_PR_3] Delta Catalog Skeleton - Delegate to InMemory Catalog - MERGED
- [FlinkSQL_PR_4] Delta Catalog - interactions with Delta Log (CreateTable and GetTable operations) - MERGED
- [FlinkSQL_PR_5] Delta Catalog - DDL option validation - MERGED
- [FlinkSQL_PR_6] Delta Catalog - interactions with Delta Log (AlterTable operation) - MERGED
- [FlinkSQL_PR_7] Delta Catalog - Restrict Table factory to work only with Delta Catalog - MERGED
- [FlinkSQL_PR_8] Delta Catalog - DDL/Query hint validation - IN PROGRESS
- [FlinkSQL_PR_9] Delta Catalog - support for Hive metastore/delegate to hive catalog.

Future
- [ ] [Release blocker] Revisit artifact packaging, as per [this comment here](https://github.com/delta-io/connectors/pull/389#issuecomment-1247076317).

TODOs
- Refactor IT tests where predefined tables are used to include a TableInfo class per table that contained the path (maybe a generator so it is always random), column names, column types, so all this information was coupled together. This class could be used for all IT tests where we use predefined Tables. ([link for context](https://github.com/delta-io/connectors/pull/487/files#r1059009008))

**Comment by kristoffSC** [comment]
FlinkSQL_PR_2 can be marked as MERGED
FlinkSQL_PR_3 can be marked as IN PROGRESS

**Comment by kristoffSC** [comment]
@scottsand-db 
A kind request (sorry, another one) for updating PR plan

To:
[FlinkSQL_PR_1] Flink Delta Sink - Table API - MERGED
[FlinkSQL_PR_2] Flink Delta Source- Table API - MERGED
[FlinkSQL_PR_3] Delta Catalog Skeleton - Delegate to InMmeory Catalog - IN PROGRESS
[FlinkSQL_PR_4] Delta Catalog - interactions with Delta Log
[FlinkSQL_PR_5] Delta Catalog - Restrict Table factory to work only with Delta Catalog
[FlinkSQL_PR_6] Delta Catalog - DDL/Query hint validation
[FlinkSQL_PR_7] Delta Catalog - support for Hive metastore/delegate to hive catalog.

**Comment by kristoffSC** [comment]
Hi @scottsand-db 
A kind request for updating PR plan

**PR PLAN:**
[FlinkSQL_PR_1] Flink Delta Sink - Table API - MERGED
[FlinkSQL_PR_2] Flink Delta Source- Table API - MERGED
[FlinkSQL_PR_3] Delta Catalog Skeleton - Delegate to InMmeory Catalog - MERGED
[FlinkSQL_PR_4] Delta Catalog - interactions with Delta Log (CraeteTable and GetTable operations) - IN PROGRESS
[FlinkSQL_PR_5] Delta Catalog - DDL option valiadation
[FlinkSQL_PR_6] Delta Catalog - interactions with Delta Log (AlterTable operation)
[FlinkSQL_PR_7] Delta Catalog - Restrict Table factory to work only with Delta Catalog
[FlinkSQL_PR_8] Delta Catalog - DDL/Query hint validation
[FlinkSQL_PR_9] Delta Catalog - support for Hive metastore/delegate to hive catalog.

**Comment by kristoffSC** [comment]
the PR plan should be updated to:

PR PLAN:
[FlinkSQL_PR_1] Flink Delta Sink - Table API - MERGED
[FlinkSQL_PR_2] Flink Delta Source- Table API - MERGED
[FlinkSQL_PR_3] Delta Catalog Skeleton - Delegate to InMmeory Catalog - MERGED
[FlinkSQL_PR_4] Delta Catalog - interactions with Delta Log (CraeteTable and GetTable operations) - MERGED
[FlinkSQL_PR_5] Delta Catalog - DDL option valiadation - MERGED
[FlinkSQL_PR_6] Delta Catalog - AlterTable operation + IT tests (1st round) - MERGED
[FlinkSQL_PR_7] Delta Catalog - Restrict Table factory to work only with Delta Catalog - MERGED
[FlinkSQL_PR_8] Delta Catalog - DDL/Query hint validation - MERGED
[FlinkSQL_PR_9] Delta Catalog - support for Hive metastore/delegate to hive catalog. - MERGED
[FlinkSQL_PR_10] Delta Catalog - add tests for reading with partition filter - support filter for partitions. - MERGED
[FlinkSQL_PR_11] Delta Catalog - add cache for DeltaLog instances in Delta Catalog. - MERGED
[FlinkSQL_PR_12] Delta Table API - UML diagrams - MERGED
[FlinkSQL_PR_13] Delta Catalog - support Table and column comments similar to Spark.
[FlinkSQL_PR_13] SQL - remove support for "mergeSchema" option - MERGED
[FlinkSQL PR_14] SQL - add SQL Examples - MERGED
**[FlinkSQL PR_15] SQL - add README.md for using SQL and Catalog support - Waiting for Review
[FlinkSQL PR_16] [FlinkSQL_tests] - examples on cluster with cloud providers. - Waiting for Review**
