### ISSUE TITLE
hadoop3 + hive3 + presto query delta lake error

### ISSUE THREAD

**Issue by kongluo** [delta-io/connectors#268]
I use hadoop3 + hive3 + presto to query the delta lake in real time. The data of delta lake can be queried normally in hive. When I use presto to query, the error Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.fs is reported. .StreamCapabilities, I manually copied the jar package of hadoop-common to presto, but it cannot be used directly with an error. Does 0.3 support querying data in hive3 through presto?

**Comment by kongluo** [comment]
The queried data is stored in azure storage gen2

**Comment by vkorukanti** [comment]
@kongluo How are you querying Delta tables from Presto? Are you using the [symlink based](https://docs.delta.io/latest/presto-integration.html) method or the new native [Delta lake connector](https://github.com/prestodb/presto/pull/16843) added in Presto?

Also please provide the full error callstack. Thanks!

**Comment by kongluo** [comment]
![deltaError](https://user-images.githubusercontent.com/28140815/155247984-deeebc5c-fb36-444a-8a43-7314109f991f.png)
i using the [symlink based](https://docs.delta.io/latest/presto-integration.html) method,
I didn't add any jar packages in presto, but an error will be reported。
Query 20220223_012821_00003_besdx failed: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.azurebfs.SecureAzureBlobFileSystem not found。Sorry for the slow response. I was engaged in other projects some time ago

**Comment by kongluo** [comment]
![image](https://user-images.githubusercontent.com/28140815/155248422-b71569af-8a68-4e33-8582-da71660220e3.png)
But when I use hive to query, I can't see the specific fields, but there is no error

**Comment by kongluo** [comment]
> @kongluo How are you querying Delta tables from Presto? Are you using the [symlink based](https://docs.delta.io/latest/presto-integration.html) method or the new native [Delta lake connector](https://github.com/prestodb/presto/pull/16843) added in Presto?
> 
> As far as I know Presto doesn't need to be copied any new jars in either approach.
> 
> Also please provide the full error callstack. Thanks!

Will there be such problems when viewing the data of azure storage Gen2 through delta Lake + Presto

**Comment by kongluo** [comment]
> 



> @kongluo How are you querying Delta tables from Presto? Are you using the [symlink based](https://docs.delta.io/latest/presto-integration.html) method or the new native [Delta lake connector](https://github.com/prestodb/presto/pull/16843) added in Presto?
> 
> As far as I know Presto doesn't need to be copied any new jars in either approach.
> 
> Also please provide the full error callstack. Thanks!

**Comment by kongluo** [comment]
> @kongluo How are you querying Delta tables from Presto? Are you using the [symlink based](https://docs.delta.io/latest/presto-integration.html) method or the new native [Delta lake connector](https://github.com/prestodb/presto/pull/16843) added in Presto?
> 
> As far as I know Presto doesn't need to be copied any new jars in either approach.
> 
> Also please provide the full error callstack. Thanks!

the presto error is :
![image](https://user-images.githubusercontent.com/28140815/155250422-44a82760-864f-46d4-8352-affa999e871d.png)

**Comment by zsxwing** [comment]
I think your Presto is missing hadoop-azure-datalake jar. I don't know how to config it. @vkorukanti are you familiar with that?

**Comment by kongluo** [comment]
> hadoop-azure-datalake jar.



> I think your Presto is missing hadoop-azure-datalake jar. I don't know how to config it. @vkorukanti are you familiar with that?

I tried to add hadoop-azure-datalake jar to Presto's hive plugin, but this problem still exists, @vkorukanti Is there a good solution to this problem？thanks.

**Comment by vkorukanti** [comment]
@kongluo Presto still depends on the Hadoop 2.7.4 which doesn't have the Azure ABFS specific implementation in it. It looks like the ABFS implementation is available from [Hadoop 2.10.0](https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-azure-datalake/). 

Few clarifications:
- The error message (ClassNotFoundException) is not expected out of the box. Expected error message is "No FileSystem for scheme: abfss". Did you add a config `fs.abfss.impl=SecureAzureBlobFileSystem`?
- Which version of `hadoop-azure-datalake` jar did you copy to `hive` plugin directory? Also did you restart the Presto coordinator and workers after adding this jar?

**Comment by kongluo** [comment]
> @kongluo Presto still depends on the Hadoop 2.7.4 which doesn't seem to have the Azure ABFS specific implementation in it. It looks like the ABFS implementation is available from [Hadoop 2.10.0](https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-azure-datalake/).
> 
> Few clarifications:
> 
> * The error message (ClassNotFoundException) is not expected out of the box. Expected error message is "No FileSystem for scheme: abfss". Did you add a config `fs.abfss.impl=SecureAzureBlobFileSystem`?
> * Which version of `hadoop-azure-datalake` jar did you copy to `hive` plugin directory? Also did you restart the Presto coordinator and workers after adding this jar?
The hadoop version uses 3.2.0. According to the official document of hadoop supporting azure gen2, the related configuration items are used, and the files for hadoop query are set through export HADOOP_OPTIONAL_TOOLS=hadoop-azure, and fs.abfss.impl=SecureAzureBlobFileSystem is added. The system is azure instead of HDFS, and the version used by hive is 3.1.2. I copied hadoop-azure-datalake from hadoop3.2 to the hive plugin of presto

**Comment by vkorukanti** [comment]
> The system is azure instead of HDFS, and the version used by hive is 3.1.2. I copied hadoop-azure-datalake from hadoop3.2 to the hive plugin of presto
This may not work as there is a major version difference between Azure lib (3.1.2) and Presto's Hadoop dependency version (2.7.4). Can you try copying the Azure lib from 2.10.1?

**Comment by kongluo** [comment]
> > The system is azure instead of HDFS, and the version used by hive is 3.1.2. I copied hadoop-azure-datalake from hadoop3.2 to the hive plugin of presto
> 
> This may not work as there is a major version difference between Azure lib (3.1.2) and Presto's Hadoop dependency version (2.7.4). Can you try copying the Azure lib from 2.10.1? If that doesn't work, will spend time tomorrow debugging this locally.


I use the azure jar package in hadoop2.10.1 version, still the same error

**Comment by zsxwing** [comment]
If you are using Spark, we actually require [Hadoop 3.2 for ADLS Gen2](https://docs.delta.io/latest/delta-storage.html#azure-data-lake-storage-gen2). IIRC, the ADLS Gen2 Hadoop connector is not available in Hadoop 3.1 and below.

https://prestodb.io/community.html has more Presto experts to help you how to config ADLS Gen2 with Presto. Maybe you can try to ask the question there?

**Comment by vkorukanti** [comment]
It doesn't look like PrestoDB has support for ADLS yet. [Issue](https://github.com/prestodb/presto/issues/11648) and a [task](https://github.com/prestodb/presto/issues/16746).

Trino has support for ADLS as they depend on Hadoop 3.2.x.

**Comment by kongluo** [comment]
> 

ok,i will try , thanks.

**Comment by kongluo** [comment]
> It doesn't look like PrestoDB has support for ADLS yet. [Issue](https://github.com/prestodb/presto/issues/11648) and a [task](https://github.com/prestodb/presto/issues/16746).
> 
> Trino has support for ADLS as they depend on Hadoop 3.2.x.

Can trino support querying delta lake data on ADLS gen2 through [symlink based](https://docs.delta.io/latest/presto-integration.html)?

**Comment by vkorukanti** [comment]
> Can trino support querying delta lake data on ADLS gen2 through [symlink based](https://docs.delta.io/latest/presto-integration.html)?
I haven't tested it, but I don't see any reason why it does work out of the box. Trino still has support for symlink and [ADLS support](https://trino.io/docs/current/connector/hive-azure.html).

**Comment by kongluo** [comment]
> > Can trino support querying delta lake data on ADLS gen2 through [symlink based](https://docs.delta.io/latest/presto-integration.html)?
> > I haven't tested it, but I don't see any reason why it does work out of the box. Trino still has support for symlink and [ADLS support](https://trino.io/docs/current/connector/hive-azure.html).


I tried to query the delta lake data on ADFS gen2 through trino, it works, thank you very much

**Comment by zsxwing** [comment]
Great to hear that it's working in Trino. Since this is because PrestoDB doesn't support Hadoop 3 yet and there is nothing Delta Lake can fix, I'm going to close this. You can add your voice to https://github.com/prestodb/presto/issues/16746 and hope they will pick up this soon 😄
