### ISSUE TITLE
Support Hive 4.0

### ISSUE THREAD

**Issue by spmp** [delta-io/connectors#273]
Considering that Hive 3 is very old and that Hive 4.0 (or simply the master branch of Hive) is close to being released, there should be a branch which builds against upstream Hive master.

I am having a go at it, but I suck and would love some assistance 8)

**Comment by zsxwing** [comment]
@spmp we are not using branches to support multiple Hive versions. Instead, we use a single jar to support both Hive 2 and Hive 3 right now.

I guess this won't work with Hive 4, but we can create a new SBT project for Hive 4 instead.

**Comment by spmp** [comment]
Sounds great @zsxwing .
I am happy to help bodging and documenting. I am pretty sure that simply deleting `HiveInputFormat.scala` as the upstream API has changed so much that the 'option' that is effect has no meaning anymore is... too basic 8)

**Comment by zsxwing** [comment]
> I am happy to help bodging and documenting. I am pretty sure that simply deleting `HiveInputFormat.scala` as the upstream API has changed so much that the 'option' that is effect has no meaning anymore is... too basic 8)

Feel free to try that. But we still need to build something in order to support Hive time travel queries. Right?

**Comment by spmp** [comment]
@zsxwing, 

> But we still need to build something in order to support Hive time travel queries. Right?

Yes.
 I think the time travel issue ( #202 ) would be best based off the result of this one.

**Comment by spmp** [comment]
There is now a Hive 4.0.0-alpha branch! https://github.com/apache/hive/tree/branch-4.0.0-alpha-1

**Comment by zsxwing** [comment]
Cool. Have you tried that?

**Comment by scottsand-db** [comment]
Hi @spmp - just following up on this issue. Have you tried what zsxwing has suggested?

**Comment by spmp** [comment]
@scottsand-db and @zsxwing, I tried earlier using my own local build of Hive 4, but had a range of issues that I thought could have been to do with `.m2` resolution of my local Hive build. Now using the published `4.0.0-alpha-1` Hive artifacts I am getting the same issues and am fairly stumped. Sorry, I am quite rusty so no surprise I am struggling 8)
I did a lot of work some time ago, but lost it, what I have recovered of this is here: https://github.com/spmp/connectors/tree/hive-4.0

I am getting build errors such as:
```
[error] connectors/hive/src/main/scala/io/delta/hive/DeltaHelper.scala:31:8: object ExprNodeEvaluatorFactory is not a member of package org.apache.hadoop.hive.ql.exec
[error] import org.apache.hadoop.hive.ql.exec.{ExprNodeEvaluatorFactory, SerializationUtilities}
[error]        ^
[error] connectors/hive/src/main/scala/io/delta/hive/DeltaHelper.scala:32:34: object plan is not a member of package org.apache.hadoop.hive.ql
[error] import org.apache.hadoop.hive.ql.plan.{ExprNodeGenericFuncDesc, TableScanDesc}
[error]                                  ^
...
...
...
[error] connectors/hive/src/main/scala/io/delta/hive/DeltaStorageHandler.scala:175:9: not found: value FunctionRegistry
[error]         FunctionRegistry.getGenericUDFForAnd(), children)
[error]         ^
[error] connectors/hive/src/main/scala/io/delta/hive/DeltaStorageHandler.scala:215:56: not found: value getConf
[error]     val snapshot = DeltaHelper.loadDeltaLatestSnapshot(getConf, new Path(deltaRootString))
[error]
```
All of which are strange to me as I can confirm that the classes are in the `hive-exec` (and `hive-matastore`) Jar in the corsair cache, and for example the `getConf` method still exists in `DeltaStorageHandler.scala` in the `4.0.0-alpha-1` branch.

**Comment by zsxwing** [comment]
How did you upgrade hive? Maybe there is some issue in the dependency list.

**Comment by spmp** [comment]
> How did you upgrade hive?

I updated the project to use the released Hive `4.0.0-alpha-1` in `build.sbt` artifacts as:
```scala
val hiveVersion = "4.0.0-alpha-1"
```
As I said, the artifacts are downloaded, and the JAR's contain the classes...

>Maybe there is some issue in the dependency list.

Maybe. I am stumped. Any ideas Scala gurus? I figure it is more of a problem associated with this project than one related to Hive.

**Comment by scottsand-db** [comment]
https://github.com/delta-io/connectors/compare/master...spmp:hive-4.0

**Comment by zsxwing** [comment]
We currently are using https://repo1.maven.org/maven2/org/apache/hive/hive-exec/3.1.2/hive-exec-3.1.2-core.jar
But Hive 4 removed this jar. Not sure why SBT doesn't fail when `"org.apache.hive" % "hive-exec" % hiveVersion % "provided" classifier "core"` doesn't exist... 

You can change the build file to depend on `hive-exec` directly. I haven't checked other issues yet. But this should make the code compile.
```
@@ -167,7 +167,7 @@ lazy val hive = (project in file("hive")) dependsOn(standaloneCosmetic) settings
   libraryDependencies ++= Seq(
     "org.apache.hadoop" % "hadoop-client" % hadoopVersion % "provided",
     "org.apache.parquet" % "parquet-hadoop" % "1.10.1" % "provided",
-    "org.apache.hive" % "hive-exec" % hiveVersion % "provided" classifier "core",
+    "org.apache.hive" % "hive-exec" % hiveVersion % "provided",
     "org.apache.hive" % "hive-metastore" % hiveVersion % "provided"
   )
 )
```

**Comment by vkorukanti** [comment]
This repo has been deprecated and the code is moved under `connectors` module in https://github.com/delta-io/delta repository. Please create the issue in repository https://github.com/delta-io/delta. See delta-io/connectors#556 for details.
