### ISSUE TITLE
Create a Delta table without specifying the table schema in Hive

### ISSUE THREAD

**Issue by cometta** [delta-io/connectors#285]
May i know is it possible when use hive 'create external table' statement without inputting each column types and let the connector auto infer the table schema or auto read the parquet's metadata?

**Comment by scottsand-db** [comment]
@zsxwing I see that you have assigned this ticket to yourself. I am just following up on its status.

**Comment by scottsand-db** [comment]
To give a response myself:

See the [delta.io:connectors > Hive > create a table](https://github.com/delta-io/connectors#create-a-hive-table) wiki which states

> the table schema in the CREATE TABLE statement must be consistent with the underlying Delta metadata. Otherwise, the connector will throw an error to tell you about the inconsistency.

**Comment by MironAtHome** [comment]
I apologies, I do not know if this feature currently supported by delta itself, however, the underlying parquet library parquet4s from version 2.+ does support reading un-specified projection of parquet file.
I am currently working on unit test / dependency version stabilization for my pull request. Once this is settled I could look into adding this feature.
It would require Scala 2.12+.

**Comment by scottsand-db** [comment]
Hi @MironAtHome, may I ask what your use case is here? i.e., what problem are you trying to solve? and what API or functionality is delta-standalone / delta-hive connector currently missing?

**Comment by zsxwing** [comment]
@MironAtHome , this is a Hive connector issue due. It's not related to Delta Standalone.

I looked at Hive code again and found we may be able to support this by introducing our own Hive SerDe. This is a prototype: https://github.com/delta-io/connectors/compare/master...zsxwing:hive-no-schema?expand=1 But I probably don't have time to work on this right now. If anyone has free time, feel free to pick up the work.

Also cc @YannByron in case you are interested.

**Comment by YannByron** [comment]
@zsxwing if want to support creating table without schema provided, i think there is no necessary to introduce our own serde. maybe just a minor optimization for `DeltaStorageHandler.preCreateTable` is ok.

**Comment by zsxwing** [comment]
As per our discussion in #323 , we will continue to investigate the Hive SerDe solution.

**Comment by vkorukanti** [comment]
This repo has been deprecated and the code is moved under `connectors` module in https://github.com/delta-io/delta repository. Please create the issue in repository https://github.com/delta-io/delta. See delta-io/connectors#556 for details.
