### ISSUE TITLE
Delta integration with Dask/ Ray

### ISSUE THREAD

**Issue by vinijaiswal** [delta-io/connectors#288]
Build a connector to integrate with Dask/Ray potentially leveraging Delta Standalone #85. This integration is requested regardless of the Python library.

Dask is an open source project, a Python parallel computing library developed to scale python packages and scientific computing workloads beyond a single machine. It provides advanced parallelism for analytics and works with the existing Python ecosystem to scale it to multi-core machines and distributed clusters. Ray provides a scheduler for Dask (dask_on_ray) which allows you to build data analyses using Dask’s collections and execute the underlying tasks on a Ray cluster.

This issue is to request a native integration of Ray with Delta Lake, to better support reinforcement learning at scale.

**Comment by zsxwing** [comment]
@vinijaiswal should we create an issue in https://github.com/delta-io/delta-rs instead since we don't plan to create a new native Python library?

**Comment by vkorukanti** [comment]
This repo has been deprecated and the code is moved under `connectors` module in https://github.com/delta-io/delta repository. Please create the issue in repository https://github.com/delta-io/delta. See delta-io/connectors#556 for details.
