### ISSUE TITLE
access delta lake from powerbi with private bucket

### ISSUE THREAD

**Issue by ryandawsonuk** [delta-io/connectors#292]
Would like to use the [powerbi connector](https://github.com/delta-io/connectors/blob/master/powerbi/README.md) but the examples are all for a public bucket. Is there an example where an access key or other credentials are needed? Or is that in other documentation that you could point to?

**Comment by dennyglee** [comment]
Thanks for the ping @ryandawsonuk - let me include @gbrueckl on this.  Thanks!

**Comment by gbrueckl** [comment]
Hi @ryandawsonuk  so basically the PowerBI connector is independent of authentication. It supports all data sources and authentication methods that are supported by Power BI already - no more, no less.
Using an Access Key to connect to ADLS or Blob Storage works out of the box, Shared Access Signatures (SAS) dont (as far as I know)
Regarding the examples in the docs:
The authentication is independent of the actual PowerQuery/M code so there would be not difference in code.
Also the examples are read-to-use so you can simply copy and paste them to try the out

if this does not help/solve your questions, please share some more details about your actual scenario

regards,
-gerhard

**Comment by vkorukanti** [comment]
This repo has been deprecated and the code is moved under `connectors` module in https://github.com/delta-io/delta repository. Please create the issue in repository https://github.com/delta-io/delta. See delta-io/connectors#556 for details.
