### ISSUE TITLE
I was surprised to find parquet4s integration first, but than even more so how dated library is

### ISSUE THREAD

**Issue by MironAtHome** [delta-io/connectors#298]
Hey, if we are using Marcin Jakubowski's parquet4s for standalone parquet read / write IO, than why is it frozen at ancient version?
I think it's time to advance platform forward, since 2.3.0 is released more than a month ago and currently 2.4.0 is about to be completed.
@mjakubowski84

**Comment by scottsand-db** [comment]
@MironAtHome - thanks for this issue. are you interested in doing that update + code changes?

**Comment by vkorukanti** [comment]
This repo has been deprecated and the code is moved under `connectors` module in https://github.com/delta-io/delta repository. Please create the issue in repository https://github.com/delta-io/delta. See delta-io/connectors#556 for details.
