### ISSUE TITLE
None of the Java example project can be run due to compilation error

### ISSUE THREAD

**Issue by kristoffSC** [delta-io/connectors#324]
All Java example projects under https://github.com/delta-io/connectors/tree/master/examples
are facing a compilation error preventing them to build and run.

The issue is that class package declaration does not reflects an actual folder structure.
![image](https://user-images.githubusercontent.com/7932805/164263215-6d889a9e-b7fa-4348-ad13-a419663d84a9.png)

To match the package declaration which is `package example` the folder structure should be like this:
`src/main/java/example`

This problem occurs in every Java example project:
1. Convert-to-delta
2. flink-example (originally was ok but was changed in PR https://github.com/delta-io/connectors/pull/305/files)
3. hello-world

To load for example a "hello-world" module as a java project you need to:
1. right click on java folder under "hello-world" module and mark it as a source root folder:
![image](https://user-images.githubusercontent.com/7932805/166804104-fe38dd22-3a80-4319-be35-32222decb956.png)
2. Right click on pom.xml -> Add as maven project
![image](https://user-images.githubusercontent.com/7932805/166804343-46fc717a-7022-4147-a5dd-2219500b2a9a.png)

**Comment by pkubit-g** [comment]
FYI 
fix for the Flink examples is provided in this PR #327

**Comment by zsxwing** [comment]
@scottsand-db Has this been fixed?

**Comment by scottsand-db** [comment]
> @scottsand-db Has this been fixed?

No it hasn't. It's currently assigned to @allisonport-db. I can take a look tomorrow as part of my on-call.

**Comment by scottsand-db** [comment]
Hi @kristoffSC - what is your, for example, `hello-world` folder marked as in IntelliJ?
