### ISSUE TITLE
[FEATURE REQUEST] Generate multiple Delta tables from single Flink sink 

### ISSUE THREAD

**Issue by Xoerk** [delta-io/connectors#344]
I'm trying to find a way to generate multiple Delta/Databricks tables when connecting to the Flink stream, from looking at the documentation of Flink connection, the Flink connecter takes the path location in the constructer which defines a single table in Delta/Databricks.

Will it be possible to dynamically define the tables based on the data stream?

**Comment by scottsand-db** [comment]
Hi @Xoerk, thanks for your question. Can you tell us a bit more about your use cases here? And give an example of what you'd like to see by `dynamically defin[ing] the tables based on the data stream`

Also, do you want to write the same, identical output to multiple output tables?

**Comment by vkorukanti** [comment]
This repo has been deprecated and the code is moved under `connectors` module in https://github.com/delta-io/delta repository. Please create the issue in repository https://github.com/delta-io/delta. See delta-io/connectors#556 for details.
