### ISSUE TITLE
Support upserts in FlinkDeltaSink

### ISSUE THREAD

**Issue by gopik** [delta-io/connectors#345]
Existing implementation supports appends only. This feature request is to support upserts in a delta table that is sorted by it's primary key columns.

Here's a rough proposal of how we could implement this - https://docs.google.com/document/d/1b35eZnIZheZK05EhNkqFMpzU3mcPze5iE9XKJulbftg/edit#heading=h.35nkun2

cc: @dennyglee

**Comment by gopik** [comment]
Depends on https://github.com/delta-io/connectors/issues/371

**Comment by marimuthuvellingiri** [comment]
Hi @gopik / @dennyglee , I am trying to integrate delta sink connector with Flink for one of my usecase which needs UPSERT mode. Can you please let us know is there any update on this issue?

**Comment by mberchon** [comment]
Hi @gopik 
Is there an ETA for this so powerful feature ? :-)

**Comment by dennyglee** [comment]
We're still working on the roadmap due to all of these awesome requests. Will try to get the roadmap updated soon. Thanks for your patience!

**Comment by jalilalchy** [comment]
@dennyglee any update on priority for this?

**Comment by dennyglee** [comment]
Thanks for your patience @jalilalchy.  While we haven't finalized the roadmap schedule, with everything else that we're working out, I'm a little concerned about the overall prioritization.  @gopik any chance you would still be interested in contributing to this?  Thanks!

**Comment by gopik** [comment]
@dennyglee Yes, I'm still interested in contributing to this feature.

**Comment by dennyglee** [comment]
Sorry for completely missing this message @gopik - my bad!  This is so awesome to hear - please ping me on [Delta Users Slack](https://go.delta.io/slack) at your convenience and we can start the convo on this, eh?!

**Comment by vkorukanti** [comment]
This repo has been deprecated and the code is moved under `connectors` module in https://github.com/delta-io/delta repository. Please create the issue in repository https://github.com/delta-io/delta. See delta-io/connectors#556 for details.
