### ISSUE TITLE
Support for Hive 3

### ISSUE THREAD

**Issue by DasariBhanu** [delta-io/connectors#36]
Hi 
I am following this connectors github link: https://github.com/delta-io/connectors/releases/v0.1.0

Hive version: 3.1.0

Added below jars to Hive CLI
delta-core-shaded-assembly_2.12-0.1.0.jar
hive-delta_2.12-0.1.0.jar

Executed below statements in Hive CLI
SET hive.input.format=io.delta.hive.HiveInputFormat;
SET hive.tez.input.format=io.delta.hive.HiveInputFormat;

Trying to create a hive external table, but facing the error : 
CREATE EXTERNAL TABLE deltaTable(col1 INT, col2 STRING)
. . . . . . . . . . . . . . . . . . . . . . .> STORED BY 'io.delta.hive.DeltaStorageHandler';
INFO : Compiling command(queryId=hive_20200407061535_6cf6b42b-ef87-4af9-b2fa-3161b15840bb): CREATE EXTERNAL TABLE deltaTable(col1 INT, col2 STRING)
STORED BY 'io.delta.hive.DeltaStorageHandler'
INFO : Semantic Analysis Completed (retrial = false)
INFO : Returning Hive schema: Schema(fieldSchemas:null, properties:null)
INFO : Completed compiling command(queryId=hive_20200407061535_6cf6b42b-ef87-4af9-b2fa-3161b15840bb); Time taken: 0.028 seconds
INFO : Executing command(queryId=hive_20200407061535_6cf6b42b-ef87-4af9-b2fa-3161b15840bb): CREATE EXTERNAL TABLE deltaTable(col1 INT, col2 STRING)
STORED BY 'io.delta.hive.DeltaStorageHandler'
INFO : Starting task [Stage-0:DDL] in serial mode
ERROR : FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. org/apache/hadoop/hive/metastore/MetaStoreUtils
INFO : Completed executing command(queryId=hive_20200407061535_6cf6b42b-ef87-4af9-b2fa-3161b15840bb); Time taken: 0.002 seconds
Error: Error while processing statement: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. org/apache/hadoop/hive/metastore/MetaStoreUtils (state=08S01,code=1)

**Comment by zsxwing** [comment]
@DasariBhanu Thanks for reporting this. We only support Hive 2.x currently. Other limitations are also documented here: https://github.com/delta-io/connectors#frequently-asked-questions-faq

**Comment by DasariBhanu** [comment]
@zsxwing Thanks for the update. Do we have any estimated time on when we can expect to support for Hive 3.x ?

**Comment by zsxwing** [comment]
We don't have a plan for Hive 3.x. We decided to choose 2.x because that's the most popular Hive major version.

@windpiger do you have any plan for Hive 3.x from your side?

**Comment by SnchitGrover** [comment]
Just my 2 cents, HDP (Hortonworks Data Platform) 3 is shipping with hive 3. Which will make use of delta + hive very limited.

**Comment by JGustavo0** [comment]
> 
> 
> Just my 2 cents, HDP (Hortonworks Data Platform) 3 is shipping with hive 3. Which will make use of delta + hive very limited.

I agrey. 

I have a customer who has now purchased the Cloudera Data Platform, with Hive 3.which complicate the use of Delta Lake, mainly because of the  Data Catalog Management, etc

**Comment by sabyasachinandy** [comment]
Any updates on this or should I make a PR?

**Comment by tdas** [comment]
Please go ahead and make a PR if you get Hive 3 working!

**Comment by tarekabouzeid** [comment]
Hi,

Do you know by which date Hive 3.x is expected be supported ? 

Best Regards,

**Comment by zsxwing** [comment]
Fixed by #151
