### ISSUE TITLE
Publishing empty source jars for `delta-standalone`

### ISSUE THREAD

**Issue by ckipp01** [delta-io/connectors#368]
If you look at the source jars that are being published for delta standalone, the source jars are just empty. For example you can see this in the latest `io.delta:delta-standalone_2.13:0.4.1` found [here](https://repo1.maven.org/maven2/io/delta/delta-standalone_2.13/0.4.1/). If you download the source jar inside you'll find it's just:

```
" zip.vim version v32
" Browsing zipfile /Users/ckipp/Downloads/delta-standalone_2.13-0.4.1-sources.jar
" Select a file with cursor and press ENTER

META-INF/MANIFEST.MF
```

The reason this matters is that for any users that are trying to use `delta-standalone` as a dependency while using [Metals](https://scalameta.org/metals/) instead of IntelliJ won't get code navigation, since it relies on source jars to ensure semanticdb gets produced.

**Comment by zsxwing** [comment]
Thanks for reporting this. This is an oversight when we refactor delta-standalone to include the shaded jackson libraries. We will investigate and see if it's possible to publish a correct source jar file.

**Comment by scottsand-db** [comment]
Same for javadocs: https://repo1.maven.org/maven2/io/delta/delta-standalone_2.13/0.4.1/delta-standalone_2.13-0.4.1-javadoc.jar

**Comment by vkorukanti** [comment]
This repo has been deprecated and the code is moved under `connectors` module in https://github.com/delta-io/delta repository. Please create the issue in repository https://github.com/delta-io/delta. See delta-io/connectors#556 for details.
