### ISSUE TITLE
ClassNotFoundException: shadedelta.org.xml.sax.helpers.DefaultHandler

### ISSUE THREAD

**Issue by chongchuanbing** [delta-io/connectors#37]
who can tell me what's this.

shadedelta.org.xml.sax.helpers.DefaultHandler

**Comment by chongchuanbing** [comment]
i can not find this class.

**Comment by zsxwing** [comment]
Could you provide steps to reproduce this issue? We shade classes to avoid conflicts with existing libraries in Hive. This is one of the shaded classes.

**Comment by zsxwing** [comment]
It would be great if you can also share the full stack trace so that we can know which place needs this class.
