### ISSUE TITLE
[delta-standalone] Create `isReadCompatible` API

### ISSUE THREAD

**Issue by scottsand-db** [delta-io/connectors#373]
Or, at the very least, investigate how this potential API relates to the existing `isWriteCompatible` SchemaUtils API

**Comment by vkorukanti** [comment]
This repo has been deprecated and the code is moved under `connectors` module in https://github.com/delta-io/delta repository. Please create the issue in repository https://github.com/delta-io/delta. See delta-io/connectors#556 for details.
