### ISSUE TITLE
Writing Delta Lake from a .NET service

### ISSUE THREAD

**Issue by remoba** [delta-io/connectors#386]
I am trying to test other ways to write to our Delta-based data lake. In other well known formats (Avro, Parquet, Json) I can easily do that in a .NET service, but it seems that's not possible with Delta.

Delta Standalone seems like the way to go for non-Spark processing, but it's only available in Scala / Java. Are there any plans to have a .NET version? Any other workaround I can try other than just trying to implement the Delta protocol by myself?

**Comment by vkorukanti** [comment]
Hi @remoba, AFAIK there are no plans for a .NET Delta log reader. Can you try the adapter for CLR to JVM mentioned [here](http://jni4net.com/)? Use this adapter to call the standalone Java APIs. Not sure of the perf implications of this adapter.

**Comment by remoba** [comment]
Hey @vkorukanti, sorry for the late reply.
I figured as much but thought I'd verify.

I don't think using jni4net is really viable in 2022, at least for us. As far as I can tell the library was last released 8 years ago (2014) and therefore also only supports .NET Framework, which is deprecated.

I guess the only thing we can really do is use a Scala / Java application, or fall back to Spark. Thanks for your time

**Comment by zsxwing** [comment]
> I guess the only thing we can really do is use a Scala / Java application, or fall back to Spark.

Yep this seems the current only option. Closing the ticket.
