### ISSUE TITLE
Performance Improvement: cache per-partition results during partition pruning

### ISSUE THREAD

**Issue by scottsand-db** [delta-io/connectors#399]
We perform partition pruning inside of [FilteredDeltaScanImpl](https://github.com/delta-io/connectors/blob/master/standalone/src/main/scala/io/delta/standalone/internal/scan/FilteredDeltaScanImpl.scala) by
- having some input query / expression `expr`
- creating a [PartitionRowRecord](https://github.com/delta-io/connectors/blob/master/standalone/src/main/scala/io/delta/standalone/internal/data/PartitionRowRecord.scala) for a given AddFile `partitionRowRecord`
- evaluating `partitionRowRecord` against `expr`

The result of this evaluation is a function of the input `expr`(fixed), the `partitionSchema` (fixed), and the AddFile partition values (variable per AddFile). We perform this evaluation [here](https://github.com/delta-io/connectors/blob/master/standalone/src/main/scala/io/delta/standalone/internal/scan/FilteredDeltaScanImpl.scala#L48).

Well, many AddFiles will have the same partition values. Thus, we can easily cache and save the evaluation result per unique partition values, and save on some computation.

**Comment by sonhmai** [comment]
@scottsand-db I would like to contribute. can you assign this issue to me?

**Comment by scottsand-db** [comment]
@sonhmai - great to hear! I will assign it to you. Cheers.

**Comment by sonhmai** [comment]
@scottsand-db 
I assumed that the number of unique combinations of partition values can be contained in memory.

Hence, I'm thinking about just adding a `mutable.Map[Map[String, String], Boolean]` in [FilteredDeltaScanImpl](https://github.com/delta-io/connectors/blob/master/standalone/src/main/scala/io/delta/standalone/internal/scan/FilteredDeltaScanImpl.scala) to cache the unique `result` of unique partitionValues combination (the immutable map from `addFile.partitionValues`. What do you think?

**Comment by scottsand-db** [comment]
Hi @sonhmai - that SGTM. @tdas - I don't expect any memory issues here, unless the user has > hundreds of thousands of partitions.

**Comment by sonhmai** [comment]
@scottsand-db should this issue be closed as the MR was merged?
