### ISSUE TITLE
Power BI Connector does not work when root path of delta table contained in function parameter

### ISSUE THREAD

**Issue by TKlerx** [delta-io/connectors#404]
Hey there,

when using power query to get the set of files for the delta connector, the following query results in an emtpy table when using the Power BI Delta connector:
```
let
    Source = AzureStorage.Blobs("some_blob_name"),
    storage = Source{[Name="some_container_name"]}[Data],
    #"Filtered Rows" = Table.SelectRows(storage, each Text.StartsWith([Name], "customers"))
in
    #"Filtered Rows"
```
This results in the following table:
![image](https://user-images.githubusercontent.com/1579185/179844771-3c8d7a99-1fc6-4d6e-92c3-1d842d38bb0e.png)

Having the first row there makes the delta connector fail.
Changing the power query to the following (only adding a trailing "/" in the filter string and thus getting rid of the first row) makes the connector work:

```
let
    Source = AzureStorage.Blobs("some_blob_name"),
    storage = Source{[Name="some_container_name"]}[Data],
    #"Filtered Rows" = Table.SelectRows(storage, each Text.StartsWith([Name], "customers/"))
in
    #"Filtered Rows"
```

I guess this could/should be handled in the Power BI connector function, if possible.

**Comment by scottsand-db** [comment]
@gbrueckl - is this something you think you could take on?
also, @TKlerx would you be interested in implementing a fix?

**Comment by gbrueckl** [comment]
sure, will have a look - should not be hard to fix

**Comment by scottsand-db** [comment]
Awesome. Assigned to you @gbrueckl !

**Comment by tdas** [comment]
@gbrueckl any update on this?

**Comment by gbrueckl** [comment]
not 100% sure but I am not able to reproduce the issue with the current/latest version.
It was probably fixed with the code that was released 3 days after this ticket was opened 
@TKlerx  can you please verify again with the latest code from this repo

**Comment by TKlerx** [comment]
Yeah, it is working now without trailing "/"
