### ISSUE TITLE
Performance Improvement: column stats based file pruning for Delta Standalone Reader.

### ISSUE THREAD

**Issue by 6a0juu** [delta-io/connectors#407]
[FilteredDeltaScan](https://github.com/delta-io/connectors/blob/master/standalone/src/main/scala/io/delta/standalone/internal/scan/FilteredDeltaScanImpl.scala) in Standalone now implemented partition filter, it is to:

* having some input query / expression expr.
* creating a [PartitionRowRecord](https://github.com/delta-io/connectors/blob/master/standalone/src/main/scala/io/delta/standalone/internal/data/PartitionRowRecord.scala) for a given AddFile partitionRowRecord.
* evaluating partitionRowRecord against expr.

In the AddFiles, there are different types of column stats documenting:

* MIN/MAX: the minimum or maximum value of a column in the file.
* NULL_COUNT: the count of null value of a column in the file.
* NUM_RECORDS: the number of records in the file.

We can implement another filter based on column stats for further performance improvement of Standalone Reader.
See [project plan in design doc](https://docs.google.com/document/d/1D2ukbGInriKTOZJl3r3pCZoQRji40rSuFgnOyzhHz7k/edit#heading=h.3959roctndfu).

**Comment by 6a0juu** [comment]
The milestone 1 (end-to-end implementation) for this feature: #403 .

**Comment by 6a0juu** [comment]
The second PR (primitive data type support) for this feature: #412 .

**Comment by 6a0juu** [comment]
The third PR (expression type support) for this feature: #413 .

**Comment by 6a0juu** [comment]
The PR support more expression type: #418 .

**Comment by vkorukanti** [comment]
This repo has been deprecated and the code is moved under `connectors` module in https://github.com/delta-io/delta repository. Please create the issue in repository https://github.com/delta-io/delta. See delta-io/connectors#556 for details.
