### ISSUE TITLE
Failed to create external table from Athena

### ISSUE THREAD

**Issue by vbattuma** [delta-io/connectors#41]
I am running the following steps to integrate Athena with Delta Lake

```
from delta.tables import *
from pyspark.sql.functions import *
deltaTable = DeltaTable.forPath(spark, "s3://test-data/input/")
deltaTable.generate("symlink_format_manifest")
```

CREATED delta_db from GLUE. 

```
CREATE EXTERNAL TABLE delta_db.mytable ( name string, hll binary )
PARTITIONED BY ( date string, partition_key string)
ROW FORMAT SERDE 'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe'
STORED AS INPUTFORMAT 'org.apache.hadoop.hive.ql.io.SymlinkTextInputFormat'
OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION 's3://test-data/input/_symlink_format_manifest/';
```

Your query has the following error(s):
FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. java.lang.UnsupportedOperationException: Unknown field type: binary

Would need help to resolve this issue to query delta table data from Athena.

**Comment by zsxwing** [comment]
This is not a connector for Athena. As you are using `DeltaTable. generate`, please create the ticket in https://github.com/delta-io/delta which provides this feature.
