### ISSUE TITLE
Flink/Delta Sink can't write to GCP

### ISSUE THREAD

**Issue by scottsand-db** [delta-io/connectors#410]
As stated in the flink [README.md's Known Limitations](https://github.com/delta-io/connectors/tree/master/flink#known-limitations) section, the latest Flink/Delta Sink version (0.5.0) only supports reading from GCP. Writing to GCP Object Storage is not supported. This is due to Flink not supporting recoverable writes to GCS, which was added in [Flink 1.15](https://issues.apache.org/jira/browse/FLINK-11838)

We should consider upgrading to Flink 1.15, or somehow backporting this change to our current connector.

**Comment by MaksGS09** [comment]
Hi!
I guess this one can be closed as support for `Flink 1.15.3` has been added to connectors?
