### ISSUE TITLE
Flink Complex Data Types  - Support for Flink v1.15.x

### ISSUE THREAD

**Issue by adriandavidsmith** [delta-io/connectors#420]
Using Flink v1.14.5 and the Respective Flink Delta Connector v0.4.1, it appears that complex data types are not supported when writing data to S3.

i.e.
```kotlin
...
val ROW_TYPE = RowType(
    listOf(
        ...
        RowType.RowField("foo", VarCharType(VarCharType.MAX_LENGTH)),
        RowType.RowField("bar", ArrayType(VarCharType())),
        ...
    )
)
...
```

yields the following
```
Caused by: java.lang.UnsupportedOperationException: Unsupported type: ARRAY<VARCHAR(1)>
	at org.apache.flink.formats.parquet.utils.ParquetSchemaConverter.convertToParquetType(ParquetSchemaConverter.java:105)
	at org.apache.flink.formats.parquet.utils.ParquetSchemaConverter.convertToParquetType(ParquetSchemaConverter.java:43)
        ...
```

This seems to be related to Flink not being able to do these conversions. Upon further investigations, this issue seems to have been fixed as part of Flink 1.15.x in following [ticket](https://issues.apache.org/jira/browse/FLINK-17782) and the following [pull request](https://github.com/apache/flink/pull/17542) respectfully. 

Looking at [documentation](https://github.com/delta-io/connectors/tree/master/flink) for the connectors, there are currently no versions of the Connectors for Flink available for Flink v1.15.x.

Looking at the [roadmap](https://github.com/delta-io/delta/issues/1307) for H2 of 2022, it does not appear that the support for Flink 1.15.x is on the agenda. 

Is there something that I may have missed as part of the documentation around writing complex data types using the Flink Delta Connector(s) which would support writing complex data types (such as arrays) using any version of the Delta Connector(s) and any version of Flink? 

If the above is correct, is there still capacity to include this support in the H2 roadmap?

**Comment by kristoffSC** [comment]
Hi, 
thanks for the feedback.

Updating to Flink 1.15 is actually under evaluation for "Flink SQL+ Table API + Catalog Support" item from the road map.

**Comment by kristoffSC** [comment]
Hi @adriandavidsmith 

0.6.0 is on Flink 1.15 which added support for writing complex types. 
I think this could be closed - WDYT @scottsand-db ?
