### ISSUE TITLE
[Feature Request]Flink Connector supports the `SupportsReadingMetadata` and `SupportsWritingMetadata` interfaces

### ISSUE THREAD

**Issue by SteNicholas** [delta-io/connectors#428]
`SupportsReadingMetadata` supports reading metadata columns and `SupportsWritingMetadata` supports writing metadata columns. Hence Flink Connector could support the `SupportsReadingMetadata` and `SupportsWritingMetadata` interfaces to read and write the metadata of Delta for query and storage of metadata.

**Comment by scottsand-db** [comment]
Hi @SteNicholas, this looks like a useful enhancement. Would you be interested in contributing this?

Also - what are "metadata" columns?

**Comment by SteNicholas** [comment]
@scottsand-db, you could refer to [FLIP-107](https://cwiki.apache.org/confluence/display/FLINK/FLIP-107%3A+Handling+of+metadata+in+SQL+connectors). I have interest to contribute this feature but need the agreement of you.

**Comment by scottsand-db** [comment]
@SteNicholas - is this only useful using SQL/Table API? Is this useful using the currently-supported DataStream API?

**Comment by scottsand-db** [comment]
Also - it's not exactly clear to me how these "metadata" columns should be persisted to the _delta_log.

**Comment by SteNicholas** [comment]
> @SteNicholas - is this only useful using SQL/Table API? Is this useful using the currently-supported DataStream API?

@scottsand-db, this is indeed useful for the Table/SQL API, because these interfaces are based on Table API.

> it's not exactly clear to me how these "metadata" columns should be persisted to the _delta_log.

The "metadata" columns are used to help to specify certain info of the writen _delta_log.

**Comment by scottsand-db** [comment]
> this is indeed useful for the Table/SQL API, because these interfaces are based on Table API.

Can you make this clearer in the issue description?

Glad you want to contribute this. Do you think you could make a PR after https://github.com/delta-io/connectors/pull/389 is merged?

**Comment by vkorukanti** [comment]
This repo has been deprecated and the code is moved under `connectors` module in https://github.com/delta-io/delta repository. Please create the issue in repository https://github.com/delta-io/delta. See delta-io/connectors#556 for details.
