### ISSUE TITLE
[QUESTION] How to connect with minIO running inside k8s cluster with Power BI using this connector?

### ISSUE THREAD

**Issue by KumudKoirala** [delta-io/connectors#430]
I am trying to connect with minio bucket / delta lake  which is currently residing inside my K8s cluster and Power BI desktop . i could not find data source connection in Power query M documentation specifically for S3/minIO storage. Any help will be appreciated
thanks

**Comment by scottsand-db** [comment]
cc @gbrueckl

**Comment by gbrueckl** [comment]
I am afraid that there is currently no connector in PowerBI that allows you to get the required file listing for the Delta Connector from an S3 storage.

The only ways to connect to S3 from PowerBI would be via API calls or Python/R scripts which will be hard to integrate with the existing Delta Connector.

In general, the connector supports all data sources supported by PowerBI as long as they can provide the required file listing

I just realized that S3 is mentioned in the docs but this is apparently wrong - will fix it in the next release!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by KumudKoirala** [comment]
thanks for the information ... I found another way to do it using delta sharing server .
