### ISSUE TITLE
[Question] How to ingest change data captured data from kafka to delta lake by Apache Flink?

### ISSUE THREAD

**Issue by ChenShuai1981** [delta-io/connectors#438]
Does Delta Flink Connector support "merge into" semantics like Delta Spark DataFrame API ?

**Comment by scottsand-db** [comment]
Hi @ChenShuai1981. The Flink-Delta connector Sink only supports appends.

https://github.com/delta-io/connectors/tree/master/flink#can-i-use-this-connector-to-append-data-to-a-delta-table

https://github.com/delta-io/connectors/tree/master/flink#can-i-use-this-connector-with-other-modes-overwrite-upsert-etc-
