### ISSUE TITLE
[BUG] Data Loss using Flink-Delta Sink on Apache Flink 1.15

### ISSUE THREAD

**Issue by scottsand-db** [delta-io/connectors#467]
The goal of this issue is to inform Flink-Delta connector users of a known data loss problem with the Flink-Delta Sink, track the status of the ongoing investigation and solution, and answer any questions that users may have.

## Overview

A user of the [flink-delta connector](https://github.com/delta-io/connectors/releases/tag/v0.5.0) reported various problems (including data loss, but also recovery crashes) while using the flink-delta sink on Flink 1.14 and 1.15. After diving into the logs, several Apache Flink bugs were found. Flink issues [FLINK-29509](https://issues.apache.org/jira/browse/FLINK-29509), [FLINK-29512](https://issues.apache.org/jira/browse/FLINK-29512), and [FLINK-29627](https://issues.apache.org/jira/browse/FLINK-29627) were created.

After these issues were resolved and their corresponding PRs merged, the data loss issues persisted. We focused our attention on the flink-delta connector and discovered the following issue.

As a reminder, the [GlobalCommitter](https://github.com/delta-io/connectors/blob/master/flink/src/main/java/io/delta/flink/sink/internal/committer/DeltaGlobalCommitter.java) is responsible for combining [DeltaCommittables](https://github.com/delta-io/connectors/blob/master/flink/src/main/java/io/delta/flink/sink/internal/committables/DeltaCommittable.java) into a [DeltaGlobalCommittable](https://github.com/delta-io/connectors/blob/master/flink/src/main/java/io/delta/flink/sink/internal/committables/DeltaGlobalCommittable.java) and then committing that file metadata into a Delta table. An assumption made during the design of the flink-delta sink was that all DeltaGlobalCommmitables for a given checkpoint X would be passed to the GlobalCommitter at the same time. Because of this assumption, the flink-delta sink had [this line of code](https://github.com/delta-io/connectors/blob/4762dccce9e45b4077ed096e9e0f79bcdd4088e3/flink/src/main/java/io/delta/flink/sink/internal/committer/DeltaGlobalCommitter.java#L221) (comparing the incoming DeltaGlobalCommittable’s checkpointId to the most recent checkpointId for this Flink application committed to the Delta table) which was used to prevent a DeltaGlobalCommittable from being committed to a Delta table twice.

However, it appears that this assumption is incorrect. Different writers produce different committables that all belong to a given checkpoint (say, committables 5.1 and 5.2 both belong to checkpoint data 5). There is no guarantee that both of these committables will be part of the DeltaGlobalCommittable that we will try to commit to the Delta table. This can be caused by dropped RPC calls or just arbitrary delay in sending data.

## Example Scenario
![Flink-Delta Sink - Data Loss Example](https://user-images.githubusercontent.com/59617782/199584202-2f9da567-5d69-4bab-be63-686689ff2d57.jpg)

## Investigation
[This design doc](https://docs.google.com/document/d/1Zy3SqVKGgRmB5xdbhn-SYm3KSqaF_9i37oZ1HPz_t5U/edit?usp=sharing) (note: still WIP) is being used to investigate the data loss issue, state our assumptions, and propose different solutions. 

Please give it a read and give us your feedback!

**Comment by scottsand-db** [comment]
Thanks @kristoffSC for working on this!

**Comment by kristoffSC** [comment]
PR ready:
https://github.com/delta-io/connectors/pull/473

**Comment by scottsand-db** [comment]
Closing since https://github.com/delta-io/connectors/pull/473 was merged.
