### ISSUE TITLE
[0.5.1 Release] [Master] Upgrade delta-storage dependency to 2.1.1

### ISSUE THREAD

**Issue by scottsand-db** [delta-io/connectors#475]
We want to pull in the various improvements to delta-storage from the delta lake 2.1.1 release https://github.com/delta-io/delta/releases/tag/v2.1.1

**Comment by vkorukanti** [comment]
This repo has been deprecated and the code is moved under `connectors` module in https://github.com/delta-io/delta repository. Please create the issue in repository https://github.com/delta-io/delta. See delta-io/connectors#556 for details.
