### ISSUE TITLE
[Feature Request] Add `vacuum` API to DeltaLog

### ISSUE THREAD

**Issue by scottsand-db** [delta-io/connectors#484]
In response to this issue https://github.com/delta-io/delta/issues/1456 we should add a vacuum API to the DeltaLog class.

This would enable users to clean up old and un-referenced parquet files.

**Comment by horizonzy** [comment]
I wish the `vacuum ` would return the AddFile list which is deleted.

**Comment by horizonzy** [comment]
@scottsand-db Hi, any progress?

**Comment by zsxwing** [comment]
This would be a good medium task for any contributor.

**Comment by vkorukanti** [comment]
This repo has been deprecated and the code is moved under `connectors` module in https://github.com/delta-io/delta repository. Please create the issue in repository https://github.com/delta-io/delta. See delta-io/connectors#556 for details.
