### ISSUE TITLE
[Feature Request] Ensure that path is available as part of PendingFileRecoverable interface

### ISSUE THREAD

**Issue by gopik** [delta-io/connectors#486]
New sink API supports getPath() and getSize(). But currently the API is returning null for getPath since we are not passing it down.

getPath() is needed for stats computation when a file is committed.

**Comment by scottsand-db** [comment]
Hi @gopik - thanks for making this issue. You seem to have some context of the code itself, would you be willing to contribute this fix?

**Comment by jalilalchy** [comment]
What exactly is meant by:

> since we are not passing it down.

Just want to clarify.

**Comment by gopik** [comment]
https://nightlies.apache.org/flink/flink-docs-master/api/java/index.html?org/apache/flink/core/classloading/package-summary.html

At this [line ](https://github.com/delta-io/connectors/blob/7edb182268639b6464f8263aab4bce5ad1efe54a/flink/src/main/java/org/apache/flink/streaming/api/functions/sink/filesystem/DeltaBulkPartWriter.java#L117)

we create a PendingRecoverable using a deprecated overload (see the javadoc). If we used the other overload, we could capture the file path and size as part of pendingrecoverable.

### Why is this important
In DeltaPendingFile, we can compute file stats if we have the actual file path (that would be published on commit). Right now we wouldn't know the file path until after commit. This implementation would enable us to have access to the path before commit. Otherwise a lot more plumbing is needed in code, we need to either have the file path in DeltaPendingFile as state, which would need serializer/deseriazer changes or we need to pass it while committing, which needs code changes in unrelated parts (like committer).

**Comment by vkorukanti** [comment]
This repo has been deprecated and the code is moved under `connectors` module in https://github.com/delta-io/delta repository. Please create the issue in repository https://github.com/delta-io/delta. See delta-io/connectors#556 for details.
