### ISSUE TITLE
Power BI - Allow Partition filters to be set via the Power Query UI

### ISSUE THREAD

**Issue by gbrueckl** [delta-io/connectors#494]
Currently, in order to leverage partition pruning, you have to manually specify the filter expression as part of code and there is no UI to make this partition filtering easier for users. 
![image](https://user-images.githubusercontent.com/11884402/214073112-f93fb552-b429-43c8-83d8-af0acbbf93cf.png)
This approach is quite powerful as it allows all kinds of filtering but is not really accessible to the unexperienced user which could result in loading the whole delta lake table to the client first and then discarding the non-matching rows again

This shall be improved so UI filters are also passed down to the Delta Lake table and the files are filtered based on the metadata in the delta_log already:
![image](https://user-images.githubusercontent.com/11884402/214074169-30c6c51f-3d71-4325-ad0c-74ebd153ade7.png)

This can be accomplished using [Table.View](https://learn.microsoft.com/en-us/powerquery-m/table-view) and the `GetRows` parameters

It will probably be a bit complicated to handle all possible selections from the UI but at least basic filters like `equals`, `greater`, `less`, `in` should be supported

**Comment by vkorukanti** [comment]
This repo has been deprecated and the code is moved under `connectors` module in https://github.com/delta-io/delta repository. Please create the issue in repository https://github.com/delta-io/delta. See delta-io/connectors#556 for details.
