### ISSUE TITLE
sql-delta-import.jar

### ISSUE THREAD

**Issue by vinitkhemka** [delta-io/connectors#511]
How can i get this jar file to connect mssql to delta lake ? Is it compatible with spark ==3.3.2 & delta lake 2.2.0 ?

**Comment by scottsand-db** [comment]
@gbrueckl can you help out here?

**Comment by gbrueckl** [comment]
Hi @vinitkhemka,

could you explain some more details of what you actually want to achieve?
read a Delta Lake table from MSSQL?
or reading data from a MSSQL database into Spark and then persist it as Delta Lake table?

**Comment by vkorukanti** [comment]
This repo has been deprecated and the code is moved under `connectors` module in https://github.com/delta-io/delta repository. Please create the issue in repository https://github.com/delta-io/delta. See delta-io/connectors#556 for details.
