### ISSUE TITLE
Delta Standalone: Jar Hell - Hadoop dependencies  

### ISSUE THREAD

**Issue by VladimirPchelko** [delta-io/connectors#541]
package size becomes too large due to Hadoop dependencies

**Comment by zsxwing** [comment]
@VladimirPchelko The package itself is not large. Do you mean when you build an uber jar that includes all jars, it's too large? Unfortunately, there is no great solution for this. We need Hadoop to access the cloud storage that's using Hadoop FileSystem APIs to provide the access.

**Comment by VladimirPchelko** [comment]
due to hadoop dependencies it is very problematic to use your project in AWS lambdas (needed uber jar) - without complicated manipulations, the packet size exceeds the limits

**Comment by zsxwing** [comment]
Unfortunately, there is little we can do. We need Hadoop to access the cloud storage that's using Hadoop FileSystem APIs. I found this StackOverflow link that may be able to use a larger jar: https://stackoverflow.com/a/72646550/1038826 Could you check if it helps?

**Comment by VladimirPchelko** [comment]
I think to use a different approach, build a separate maven project, which
will contain only really used libraries from hadoop (for example -
exclude aws-sdk-bom (hadoop-aws), include aws-sdk-s3)

пт, 28 апр. 2023 г. в 18:09, Shixiong Zhu ***@***.***>:

**Comment by scottsand-db** [comment]
@VladimirPchelko - did this new approach work for you?

**Comment by VladimirPchelko** [comment]
Yes, it works. At first, it allows me to exclude aws-java-sdk-bom - it
greatly reduces the size of uber jar.

Many things like yarn, kafka, ,zookeeper, mapreduce, etc. are not needed
for the functionality of Hadoop filesystems (S3 and DBFS).

чт, 4 мая 2023 г. в 21:41, Scott Sandre ***@***.***>:

**Comment by ahmedriza** [comment]
Would not it be better not to rely on the Hadoop libraries for cloud storage access, since all cloud storage providers have pure Java APIs.   

For example, we turned to Deltalake (and cloud storage) to move completely away from Hadoop, but now we find again having to depend on Hadoop libraries in order to use Deltalake, which to my mind doesn't make much sense.
