### ISSUE TITLE
 [Delta-Standalone] create table

### ISSUE THREAD

**Issue by VladimirPchelko** [delta-io/connectors#544]
missing api to create table if not exists

**Comment by scottsand-db** [comment]
Hey - `DeltaLog.forTable(conf, path)` will create the table if it doesn't exist. Is this not working as expected for you?

**Comment by vkorukanti** [comment]
This repo has been deprecated and the code is moved under `connectors` module in https://github.com/delta-io/delta repository. Please create the issue in repository https://github.com/delta-io/delta. See delta-io/connectors#556 for details.
