### ISSUE TITLE
Maturity custom connector delta

### ISSUE THREAD

**Issue by mvdwielen** [delta-io/connectors#548]
Hi, we are developing data products stored as delta lake tables on ADLS Gen 2. We are considering to use this customer connector to import the delta lake date in to a tabular model and have the following questions:"

- Is it possible to use this custom connector in Visual Studio Professional Tabular project as well?
- Is it possible to use this customer connector in Tabular Editor as well?
- How stable is this custom connector and is it secure and mature enough to productionize the solution?

**Comment by tdas** [comment]
These are questions about Tabular product... not about Delta Lake. I am not sure how to help. This might not be the right place to ask this.

I am not going to close this. Feel free to reopen if you have Delta specific questions.
