### ISSUE TITLE
Cannot build this project due to dependencies with CVEs

### ISSUE THREAD

**Issue by ahmedriza** [delta-io/connectors#551]
We cannot build this project due to dependencies on libraries that have multiple CVEs against them.  Examples:

```
log4j-core-2.10.0
log4j-core-2.6.2
```
Our corporate repository explicitly blocks these due to CVEs and those are really old versions which have been superseded for quite some time.

**Comment by vkorukanti** [comment]
This repo has been deprecated and the code is moved under `connectors` module in https://github.com/delta-io/delta repository. Please create the issue in repository https://github.com/delta-io/delta. See delta-io/connectors#556 for details.
