### ISSUE TITLE
Proposal: Unify this Delta Connectors and Delta-Spark codebases

### ISSUE THREAD

**Issue by tdas** [delta-io/connectors#556]
In [Nov 2019](https://github.com/delta-io/connectors/commit/6dde85d87581cac4344ad702055b872946fc56b1), Delta Connectors repo started as an incubator project to foster the independent development of the non-spark connectors allowing the project to proceed with a different cadence than the Delta/Spark connector in the original Delta repo ([www.github.com/delta-io/delta](http://www.github.com/delta-io/delta)). Almost 4 years later, we have multiple popular and stable connectors now
Standalone - Enjoys ~40K downloads/month, and has enabled building many connectors (the following ones in this repo, and external ones like PrestoDB, Pulsar, Apache Beam).
Flink - Processing 100s of TB/day at a premier food delivery company
Hive2 and Hive3 
PowerBI

While we have enjoyed the advantage of being able to move at a faster pace to reach this scale than the Delta-on-Spark, as maintainers, we are currently facing a few major downsides.

- Complex dependencies of modules across repos - Delta Standalone project in connectors repo depends on the Delta Storage project (Maven artifact delta-storage) in the original Delta repo (delta-io/delta). Furthermore, newer initiatives like Delta Kernel are located in that original repo (since it hosts the protocol), and will create further cross-repo dependencies.

- Maintenance overheads - Each repo has its own release cycle, thus requiring two sets of releases every quarter. As project maintainers, this is double the overhead which causes releases to be slowed down.

To improve this situation in the future, I propose we merge the connectors code into the original Delta repo. We will unify the release cycles of Delta/Spark and Delta Connectors.

**Comment by dennyglee** [comment]
I think this is a great idea and due to its maturity, will simplify maintenance.

**Comment by tdas** [comment]
This is cross-listed in the delta repo as well, https://github.com/delta-io/delta/issues/1824

**Comment by tdas** [comment]
All the code in this repo has been merged with full history in the original delta repo. Closing this issue. 
We will mark this repo has deprecated and communicate with all the open PRs and issues appropriately.

**Comment by vkorukanti** [comment]
## Steps to migrate existing PR on [delta-io/connectors](https://github.com/delta-io/connectors) to [delta-io/delta](https://github.com/delta-io/delta).
- Create a patch file with the diff of the PR by appending `.patch` after the PR link.
   - For example: `https://github.com/delta-io/connectors/pull/559.patch`
   - Save the patch content locally in a file.
- Update the file paths in the locally saved file by prepending a "connectors/" in each path. 
- Apply the path file in your local repository of [delta-io/delta](https://github.com/delta-io/delta)
