### ISSUE TITLE
Missing Doc/Readme.md for Flink SQL and Delta Connector

### ISSUE THREAD

**Issue by kristoffSC** [delta-io/connectors#561]
PR for merging SQL support [[1]](https://github.com/delta-io/connectors/pull/555) was missing SQL_PR15 [[2]](https://github.com/delta-io/connectors/pull/538) that added documentation for SQL support in Flink connector even though it was merged into [flink_table_catalog_feature_branch](https://github.com/delta-io/connectors/tree/flink_table_catalog_feature_branch).

My best guess for what happened is that at one point flink_table_catalog_feature_branch must have been rebased in such a way that my original PR_15 was removed.
We can see that it was already reviewed and merged to the feature branch:
https://github.com/delta-io/connectors/pull/538

[1] https://github.com/delta-io/connectors/pull/555
[2] https://github.com/delta-io/connectors/pull/538

**Comment by kristoffSC** [comment]
This issue is solved by https://github.com/delta-io/connectors/pull/559

**Comment by kristoffSC** [comment]
@tdas ^

**Comment by vkorukanti** [comment]
This repo has been deprecated and the code is moved under `connectors` module in https://github.com/delta-io/delta repository. Please create the issue in repository https://github.com/delta-io/delta. See delta-io/connectors#556 for details.
