### ISSUE TITLE
Delta Standalone Reader doesn't work with jackson-moudle-scala 2.10.0

### ISSUE THREAD

**Issue by zsxwing** [delta-io/connectors#63]
Due to the binary incompatible change in jackson-moudle-scala 2.10.0,  the following line in `JsonUtils` is compiled with jackson-moudle-scala 2.6.7.1, and it doesn’t work when jackson-moudle-scala 2.10.0 is on the classpath.

```
val mapper = new ObjectMapper with ScalaObjectMapper
```

**Comment by vivin** [comment]
Any updates on this?

**Comment by zsxwing** [comment]
Closing this as a duplicate of #137.
