### ISSUE TITLE
Create Hive table from Delta Lake using HiveQL

### ISSUE THREAD

**Issue by dvdgnzlz-maths** [delta-io/connectors#71]
Hi everyone,

I try to create one table in Hive from Delta lake but the Hive shell return me the following message:

> Error: org.apache.hive.service.cli.HiveSQLException: Error while processing statement: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. java.lang.IllegalArgumentException: a StructType must have at least one field

I have the next delta table:

```

> scala> spark.read.format("delta").load(pathToEventsTable).show
> +-------+-----+--------+------+-----------+
> |   date|delay|distance|origin|destination|
> +-------+-----+--------+------+-----------+
> |1011245|    6|     602|   ABE|        ATL|
> |1020600|   -8|     369|   ABE|        DTW|
> |1021245|   -2|     602|   ABE|        ATL|
> |1020605|   -4|     602|   ABE|        ATL|
> |1031245|   -4|     602|   ABE|        ATL|
> |1030605|    0|     602|   ABE|        ATL|
> |1041243|   10|     602|   ABE|        ATL|
> |1040605|   28|     602|   ABE|        ATL|
> |1051245|   88|     602|   ABE|        ATL|
> |1050605|    9|     602|   ABE|        ATL|
> |1061215|   -6|     602|   ABE|        ATL|
> |1061725|   69|     602|   ABE|        ATL|
> |1061230|    0|     369|   ABE|        DTW|
> |1060625|   -3|     602|   ABE|        ATL|
> |1070600|    0|     369|   ABE|        DTW|
> |1071725|    0|     602|   ABE|        ATL|
> |1071230|    0|     369|   ABE|        DTW|
> |1070625|    0|     602|   ABE|        ATL|
> |1071219|    0|     569|   ABE|        ORD|
> |1080600|    0|     369|   ABE|        DTW|
> +-------+-----+--------+------+-----------+
> only showing top 20 rows

> scala> spark.read.format("delta").load(pathToEventsTable).schema
> res22: org.apache.spark.sql.types.StructType = StructType(StructField(date,IntegerType,true), StructField(delay,IntegerType,true), StructField(distance,IntegerType,true), StructField(origin,StringType,true), StructField(destination,StringType,true))

> scala> print(pathToEventsTable)
> /tmp/departureDelays.delta`
```

I run CREATE TABLE in Hive shell:

```
CREATE EXTERNAL TABLE delta_tbl(`date` bigint, delay bigint, distance bigint, origin string, destination string)
STORED BY 'io.delta.hive.DeltaStorageHandler'
LOCATION '/tmp/departureDelays.delta';
```
or else

```
CREATE EXTERNAL TABLE delta_tbl(`date` bigint, delay bigint, distance bigint, origin string, destination string)
ROW FORMAT SERDE 'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe'
WITH SERDEPROPERTIES("path" = "/tmp/departureDelays.delta'")
STORED BY 'io.delta.hive.DeltaStorageHandler'
LOCATION 'file:///tmp/departureDelays.delta';
```

Does anyone know what can happen?

Thanks in advance.
Best regards,

**Comment by zsxwing** [comment]
If you need to query the table in Spark, you need to use Spark to create a Spark data source table such as 
```
CREATE TABLE foo(str STRING) USING delta LOCATION ....
```

If you need to query the table in Hive, you need to use Hive to create a Hive table such as 
```
CREATE EXTERNAL TABLE deltaTable(col1 INT, col2 STRING)
STORED BY 'io.delta.hive.DeltaStorageHandler'
LOCATION '/delta/table/path'
```

A table created by Spark cannot be queried by Hive and vice versa.

**Comment by dvdgnzlz-maths** [comment]
Thanks @zsxwing for your answer.

Finally you can run the query. The thing is that I have a docker-compose and, I didn't realize that the files were in different volumes (a Spark container and another Hive container)

I have been able to create from a DeltaTable a table in Hive.
`
CREATE EXTERNAL TABLE delta_tbl(`date` int, delay int, distance int, origin string, destination string)
ROW FORMAT SERDE 'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe'
WITH SERDEPROPERTIES("path" = "/tmp/departureDelays.delta'")
STORED BY 'io.delta.hive.DeltaStorageHandler'
LOCATION 'file:///tmp/departureDelays.delta';`

Thank you very much for your help.
Best regards

**Comment by premsagarreddy** [comment]
> If you need to query the table in Spark, you need to use Spark to create a Spark data source table such as
> 
> ```
> CREATE TABLE foo(str STRING) USING delta LOCATION ....
> ```
> 
> If you need to query the table in Hive, you need to use Hive to create a Hive table such as
> 
> ```
> CREATE EXTERNAL TABLE deltaTable(col1 INT, col2 STRING)
> STORED BY 'io.delta.hive.DeltaStorageHandler'
> LOCATION '/delta/table/path'
> ```
> 
> A table created by Spark cannot be queried by Hive and vice versa.

Hi @zsxwing 

we have Hive 1.2.1000.2.6.5.1175-1 on hortonworks Hadoop cluster, But I am not able to create delta tbale using hive. My requirement is, I should be able to write to delta tbale which I created using hive and vice-versa. Please suggest; Thanks

**Comment by zsxwing** [comment]
> we have Hive 1.2.1000.2.6.5.1175-1 on hortonworks Hadoop cluster, But I am not able to create delta tbale using hive.

@premsagarreddy I don't use hortonworks so I don't know what open source Hive version `1.2.1000.2.6.5.1175-1` maps to. Could you provide it if you know about it? In addition, could you provide the error when you create a Delta table using hive? It would be great if you can create a new issue so that we can continue our discussion there?
