### ISSUE TITLE
Deltalake Atlas Connector

### ISSUE THREAD

**Issue by dvdgnzlz-maths** [delta-io/connectors#72]
Hi everyone,

This Databricks article 

> https://databricks.com/discover/data-lakes/best-practices

discusses the possibility of using Apache Atlas for Data Cataloguing.

> There are a number of software offerings that can make data cataloguing easier. The major cloud providers offer their own proprietary data catalog software offerings, namely Azure Data Catalog and AWS Glue. Outside of those, Apache Atlas is available as open source software, and other options include offerings from Alation, Collibra, and Informatica, to name a few.

I'm working with this idea. The problem is that there is no connector for Delta Lake and Atlas. I am trying to use the Spark connector that comes in Apache Atlas (built by Hortonwork) but I have compatibility problems. The thing is that the connector that use Apache Atlas has a Scala 2.11 version and Delta v0.7+ versions use Spark 3.0 with a Scala 2.12 version, so I can't connect it.

With Spark version 2.4 and Delta v0.6, I have been able to create an External Table from a file written in "delta" format. I have tried to make a "folk" of the Spark-Atlas-Connector project but there are dependencies that are written in Scala 2.11 that do not have Hortonwork released.

![image](https://user-images.githubusercontent.com/54352971/104709557-611faa80-571f-11eb-814c-57319eb0312e.png)

Any idea how I can evolve this theme?

Thanks in advance.
Best,

**Comment by dennyglee** [comment]
Are you using this [spark-atlas-connector](https://github.com/hortonworks-spark/spark-atlas-connector)?  If so, yes I'm a little concerned as it has not been updated to Spark 3.0 and the Delta project is very much focusing on Spark 3+ due to the performance improvements included (AQE, dynamic partition pruning, catalog API, etc.)

**Comment by vkorukanti** [comment]
This repo has been deprecated and the code is moved under `connectors` module in https://github.com/delta-io/delta repository. Please create the issue in repository https://github.com/delta-io/delta. See delta-io/connectors#556 for details.
