### ISSUE TITLE
Flink Connector

### ISSUE THREAD

**Issue by aleksandersumowski** [delta-io/connectors#74]
it would be amazing if it was possible to read Delta formatted data in Apache Flink

**Comment by zsxwing** [comment]
We have built Delta Standalone Reader so this should make the Flink connector easier to build. If anyone familiar with Flink would like to build it, I'm happy to advise how to use Delta Standalone Reader APIs.

**Comment by darkknight100** [comment]
Hey @zsxwing @dennyglee  I would like to nominate myself for the Flink connector. I have some experience with Apache Flink for around 1.5 years.

**Comment by dennyglee** [comment]
That would be great, Vaibhav!   Is there anything we can do to help?  Would
it help if we jumped onto a Flink/Delta sync some time?

Sent via Superhuman ***@***.***>

**Comment by darkknight100** [comment]
Thanks Denny for the reply. Yes, that would be a better way to start things.

**Comment by darkknight100** [comment]
Thanks Denny for the reply. Yes, that would be a better way to start things.

**Comment by dennyglee** [comment]
Cool!  Could you join the Delta Users Slack (https://dbricks.co/delta-users-slack) and we can continue the conversation and schedule there?  Thanks!

**Comment by maver1ck** [comment]
@darkknight100 Do you need any help with this ?

**Comment by dennyglee** [comment]
Hi @maver1ck - if you’re up for joining the effort on the Flink/Delta connector, please join us on the Delta Users Slack (https://dbricks.co/delta-users-slack) and join the Flink-Delta-Connector channel.  We have syncs every two weeks, eh?!  HTH!

**Comment by tdas** [comment]
I am closing because this is not tracked in finer granularity in #175 and #110
