### ISSUE TITLE
Cannot view columns from Delta Hive tables in DBeaver or when connecting to PowerBI

### ISSUE THREAD

**Issue by chrisjkeeney** [delta-io/connectors#77]
I'm using PySpark to save Delta-Hive tables for Spark Thrift Server to access so the data can be queried externally or connected to a BI Tool such as PowerBI. When trying to load the table into PowerBI directly, I get the error `This query does not have any columns with the supported data types. It will be disabled from loaded to the model`. However, when I do a custom SQL query import using `SELECT * FROM delta_table;` it loads just fine.

When viewing the table in DBeaver, I'm able to query the tables, but cannot see any information or metadata regarding the data. I'm guessing this is because the Delta connector only gives HIVE enough information to create the tables. Are there ways I can access the metadata via a Hive connection or are there other ways I should be approaching this?

**Comment by dennyglee** [comment]
Hive is basically the pointer to the location of the Delta table - the schema and metadata are located in the `_delta_log` folder.  I do not believe DBeaver is able to read the Delta table transaction log so if your Delta table has many transactions in it, you may be reading all of the Parquet data (i.e. duplicate data) vs. just the current snapshot (or whichever snapshot you would like).

Saying this, there is an early experimental [Power BI connector](https://github.com/gbrueckl/PowerBI/tree/main/PowerQuery/DeltaLake) that may be worth exploring

**Comment by chrisjkeeney** [comment]
Thanks for the reply! I’m using Spark Thrift Server to do general purpose queries on the Hive tables and it appears Delta Lake isn’t able to do that as of yet. Is my intuition correct there?

Looks like Databricks has a way to do this using their internal Delta Engine, but I can’t find any information on using Spark Thrift Server with Delta Tables

**Comment by dennyglee** [comment]
No problem at all, yes your intuition is correct because the general purpose queries on the Hive tables (via Thrift) is obtaining all of the metadata from Hive.  The metadata for a Delta table is stored directly into the file system (same folder as the table). I forgot to mention perhaps you can use the [Hive connector](https://github.com/delta-io/connectors) and see if that helps?

**Comment by zsxwing** [comment]
The question is answered. Closing this.
