### ISSUE TITLE
Delta Standalone writer

### ISSUE THREAD

**Issue by lmichelbacher** [delta-io/connectors#85]
Are there any plans for a standalone writer?

**Comment by dennyglee** [comment]
Not in the short term but please check out the https://github.com/delta-io/kafka-delta-ingest as part of the Delta RS project on its ongoing project for a standalone writer.

**Comment by zsxwing** [comment]
Hey, @lmichelbacher we are working on the design right now. It would be great if you can provide some details of your potential usage. For example, how are you going to use this? Do we want the library to generate parquet files for you, or you just want to commit some your parquet files to a Delta table?

**Comment by lmichelbacher** [comment]
👋 Hi, 

What I have in mind are use cases where you stream data into Delta Lake tables on S3. The ideal match would be a library that I can run in an AWS Lambda function that is triggered by events on a Stream like Kinesis or Kafka. The events on the stream can be creates, updates or deletes and I'd like those to be enacted on Delta Lake tables as quickly as possible.

To achieve this currently, I need to rely on Spark. I haven't tried to spin up Spark inside a Lambda function but it sounds like an anti-pattern. The alternatives (to my knowledge) are non-serverless solutions (e.g. a custom Kinesis client running on EC2) or Spark streaming (e.g. an AWS Glue).

As you can see, I'm leaning towards serverless on AWS. That's the ecosystem in which a stand-alone writer would be most valuable to my organization.

**Comment by zsxwing** [comment]
@lmichelbacher I see. Are you going to batch events? Delta Lake is not design for frequent small writes. In addition, do you need APIs to write data, or you can write parquet files by yourself and then tell Delta Standalone Writer to add these files to the table?

**Comment by haridy** [comment]
Hello everyone, I am facing the same design choices that @lmichelbacher is considering and wanted to show support for the standalone (python) writer. The idea is to use a serverless function (for me on Azure) that is triggered by events on Kafka (single or batched, likely batched) and write the updates to a streaming table on Delta Lake. I think what's currently available on delta-rs can do that, is that correct ?

**Comment by dennyglee** [comment]
@haridy In your scenario, utilizing the Rust API certainly sounds like something you could _potentially_ do.  Perhaps jump on the Delta Users Slack in the Rust API channel and we can further discuss there?

**Comment by scottsand-db** [comment]
Here's our Design Requirements and Proposal Sketch document for the Delta Standalone Writer (DSW). Feel free to add your comments on this github issue.

[[2021-09-13] Delta Standalone Writer Public Document](https://docs.google.com/document/d/1MJhmW_H7doGWY2oty-I78vciziPzBy_nzuuB-Wv5XQ8/edit?usp=sharing)

**Comment by zsxwing** [comment]
Closing this. We have merged all of Delta Standalone Writer changes to the master branch. Will make a release soon.

**Comment by young-druid** [comment]
Hi, I hope it is a right place to ask questions about this feature. In the proposal to this feature it is written:
```
The DSW would enable developers to build connectors so other streaming engines like Flink, Kafka, and Pulsar can write into Delta tables, too.
```
and
```
Java APIs for developers to write a Delta table with ACID guarantee (except S3 with multiple JVMs; see Out-of-Scope)
```
Was there an expectation that Standalone writer is always run in a single JVM? Was it designed to be run in K8S? If yes does it mean I should always run a single pod with DSW?

**Comment by scottsand-db** [comment]
Hi @young-druid, yes, Delta Standalone runs in a single JVM. Whereas Delta Lake uses Spark to read + write to the transaction log, Delta Standalone is distinctly Spark-less and so we use single-JVM parquet and json libraries to read + write to the transaction log.

It should be able to be run anywhere that supports JVM applications, so like you said, it must be run within a single node/pod.

**Comment by gumartinm** [comment]
Sorry to bother you @scottsand-db 

This PR https://github.com/delta-io/delta/pull/1044, does not work with Delta Standalone?

**Comment by scottsand-db** [comment]
Hi @gumartinm. In Delta Lake 1.1, we released a new `delta-storage` artifact, as well as the `delta-storage-s3-dynamodb` artifact. Both of these artifacts are spark-less.

We are in the process of updating `delta-standalone` to depend on `delta-storage`. This means that we will be able to consolidate the LogStore implementations. And, to answer your question, this means that delta-standalone will be able to use the S3 multi-cluster write solution (using the `delta-storage-s3-dynamodb` artifact).

**Comment by scottsand-db** [comment]
To be clear,

> Oh, nevermind, I guess it only works with Spark.

This is true for now, but once we update Delta Standalone, it will be able to use the S3DynamoDBLogStore.

**Comment by prdpsvs** [comment]
Is it possible to apply non-partition column as a filter using scan.getResidualPredicate() function? The [link ](https://github.com/delta-io/connectors/blob/master/standalone/src/main/java/io/delta/standalone/DeltaScan.java)states that  filtering is only supported on partition columns and users should use DeltaScan#getResidualPredicate() to check for any unapplied portion of the input predicate.  However, [this example](https://docs.delta.io/latest/delta-standalone.html#starting-a-transaction-and-finding-relevant-files) states that non partition filters can also be applied and used zappy engine. Could you share the zappy library apply non partition filters or alternatives to prune non-partition filters?

**Comment by scottsand-db** [comment]
Zappy is just some example engine. It doesn't exist. `Please note that this example uses a fictitious, non-Spark engine Zappy to write the actual parquet data`

> Is it possible to apply non-partition column as a filter using scan.getResidualPredicate() function?
For sure, but you will have to implement this yourself.
