### ISSUE TITLE
Can you use this hive connector with pyspark?

### ISSUE THREAD

**Issue by cynthiavincent** [delta-io/connectors#90]
I see the configuration provided for scala and java and the usage for the same. Is there a way to read delta lake tables using hive by creating external tables using pyspark? 
Or do I need to create external tables on presto and access the tables from there?

**Comment by zsxwing** [comment]
You can create the tables using PySpark. However, in order to read such tables in Hive, you need to register it in Hive Metastore using Hive CLI using the following syntax:

```
CREATE EXTERNAL TABLE deltaTable(col1 INT, col2 STRING)
STORED BY 'io.delta.hive.DeltaStorageHandler'
LOCATION '/delta/table/path'
```
