### ISSUE TITLE
Hive create external table giving error ..

### ISSUE THREAD

**Issue by arun990** [delta-io/connectors#92]
After having the Deltatable and with some delta data at the location, attemped to create external table by following the steps mentioned in https://github.com/delta-io/connectors for hive connector, got the below error.
Appreciate you advise on how to address it.

FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. org/apache/hadoop/hive/metastore
/MetaStoreUtils

**Comment by zsxwing** [comment]
Which Hive version are you using?

**Comment by arun990** [comment]
Hi zsxwing,

Got the above shared error in Hive 3.x and understood that Hive 3.x is not supported.
Then changed to the environment with Hive 2.x version and getting the similar below error for Hive 2.3.7 when attempted 
to create external table.
error on Hive:
FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. com.google.common.util.concurren
t.UncheckedExecutionException: java.lang.ArrayIndexOutOfBoundsException: 12111

tried the same create external table statement on Beeline:
Error: Error while compiling statement: FAILED: SemanticException Cannot find class 'io.delta.hive.DeltaStorageHandl
er' (state=42000,code=40000)

**Comment by zsxwing** [comment]
> FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. com.google.common.util.concurren
> t.UncheckedExecutionException: java.lang.ArrayIndexOutOfBoundsException: 12111

This is something new. Could you find the full stack trace and post it here?

**Comment by arun990** [comment]
Have changed the Delta connector Hive jars  (from v0.2.0) to v0.1.0 and then getting the similar (slightly modified) Hive error as below:

Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. java.lang.ArrayIndexOutOfBoundsException: 17418

The error is happening when attempted to create external table from Hive.
Can you just give some tips on how to get/generate full stack trace for this Hive error and will surely share it.

**Comment by zsxwing** [comment]
Looks like this is the same as #88. Closing it as a duplicated ticket.
