### ISSUE TITLE
delta lake 1.0.0 support

### ISSUE THREAD

**Issue by jdonnelly-apixio** [delta-io/connectors#95]
Hey,

Does 0.2.0 of the connector support delta lake 1.0.0? If not, are there any plans to support it?

Thanks,
Jon

**Comment by zsxwing** [comment]
Since Delta Lake 1.0.0 doesn't introduce any reader side incompatible change, you should be able to use this connector to read tables written by Delta Lake 1.0.0.

**Comment by jdonnelly-apixio** [comment]
Awesome, thank you.
