### ISSUE TITLE
Unable to compile sql-delta-import

### ISSUE THREAD

**Issue by serdarmutlu** [delta-io/connectors#97]
Trying to compile sql-delta-import, but facing the following error. I face same error with hive-tez too.

<my_server>:~/connectors-master$ build/sbt sql-delta-import/compile
Using /usr/lib/jvm/java-8-openjdk-amd64 as default JAVA_HOME.
Note, this will be overridden by -java-home if it is set.
[info] Loading project definition from ~/connectors-master/project
[info] Set current project to connectors-master (in build file:~/connectors-master/)
[error] Expected ID character
[error] Not a valid command: sql-delta-import
[error] Expected project ID
[error] Expected configuration
[error] Expected ':' (if selecting a configuration)
[error] Expected key
[error] Not a valid key: sql-delta-import
[error] sql-delta-import/compile
[error]                 ^

**Comment by jaceklaskowski** [comment]
That looks like a user error not connector's and should really go to https://groups.google.com/g/delta-users.

Please send an email to the forum and close this "issue". Thank you.

**Comment by serdarmutlu** [comment]
I was able to compile other components like standalone, and hive. I faced problem with sql-delta-import, and hive-tez. Hence I don't believe it is user error.

Anyway, I compiled sql-delta-import with Intellij.

Closing this issue.

**Comment by zsxwing** [comment]
@serdarmutlu The command should be `build/sbt sqlDeltaImport/compile`.
