### ISSUE TITLE
PowerBI dataset doesn't refresh with Delta connector and Data Lake Gen2

### ISSUE THREAD

**Issue by carlosg-m** [delta-io/connectors#99]
I'm using the Delta connector with a Data Lake Storage Gen2 source. When in PowerBI desktop everything works, I can preview the tables and refresh the content, and the experience is flawless.
```
= fn_ReadDeltaTable(AzureStorage.DataLake("https://Data_Lake_URL_to_Delta_table"), [])
```

However, after publishing the dashboard, it's no longer possible to refresh the dataset. 
The error is related with the dataset not being a dynamic data source.

```
Something went wrong
This dataset includes a dynamic data source. Since dynamic data sources aren't refreshed in the Power BI service, this dataset won't be refreshed. Learn more: https://aka.ms/dynamic-data-sources.
Please try again later or contact support. If you contact support, please provide these details.
```

**Comment by carlosg-m** [comment]
I used @gbrueckl's version and it fixed the issue.
- https://github.com/gbrueckl/connectors/blob/master/powerbi/fn_ReadDeltaTable.pq

You should consider update this repository.

I'm going to take this opportunity to thank the author @gbrueckl. 

Amazing work it really saved me a lot of time, our old setup was using Azure Data Lake, SQL Server and PowerBI and it was taking 2h in SQL Server and 1h:30m in PowerBI. 

Now it takes only 15 minutes to import the data in PowerBI and the SQL Server is no longer required.

**Comment by gbrueckl** [comment]
yes, it is already fixed in my fork 
the PR to also get the fix into this repo is open and I am waiting for @dennyglee to finally approve it ;)

**Comment by dennyglee** [comment]
Yeah, this is my bad - I'm merging #94 as we speak.
